'use strict';

const screens=['cover','guide','map','itinerary','bookings','kids','final'];
let current=0, guideIndex=0, mapIndex=0, dayIndex=0, reserveTab='hotels';
let map=null, audio=null;
const storageKey='nusa_v7_iria_izan_ideas';

const IMG={
  temple:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=88',
  rice:'https://images.unsplash.com/photo-1559628233-100c798642d4?auto=format&fit=crop&w=1600&q=88',
  beach:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=88',
  snorkel:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=88',
  waterfall:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=88',
  villa:'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=88',
  plane:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=88',
  food:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=88',
  sunset:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88',
  hotel:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=88'
};

const points=[
  {name:'Denpasar',x:24,y:79,coords:[-8.7467,115.1668],days:'Día 1 y salida',cost:'18-35 € traslado coche',img:IMG.plane,text:'Entrada y salida internacional. Si se llega tarde, plan suave.',waze:'https://waze.com/ul?ll=-8.7467,115.1668&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Ngurah%20Rai%20International%20Airport'},
  {name:'Ubud',x:34,y:57,coords:[-8.5069,115.2625],days:'Días 2-5',cost:'75-180 €/noche hotel boutique',img:IMG.rice,text:'Base de arrozales, templos, cafés, spa y excursiones a cascadas.',waze:'https://waze.com/ul?ll=-8.5069,115.2625&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Ubud%20Bali'},
  {name:'Sidemen',x:47,y:52,coords:[-8.4667,115.4333],days:'Día 6',cost:'45-70 € coche privado día',img:IMG.rice,text:'Valle menos masificado para dormir o hacer parada escénica.',waze:'https://waze.com/ul?ll=-8.4667,115.4333&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Sidemen%20Bali'},
  {name:'Padang Bai',x:55,y:65,coords:[-8.5311,115.5082],days:'Ferry',cost:'35-65 € p/p ferry orientativo',img:IMG.beach,text:'Puerto para cruce a Gili. Mejor barco de mañana y margen.',waze:'https://waze.com/ul?ll=-8.5311,115.5082&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Padang%20Bai%20Harbour'},
  {name:'Gili Meno',x:70,y:46,coords:[-8.3517,116.0584],days:'Días 7-10',cost:'80-210 €/noche hotel playa',img:IMG.snorkel,text:'Isla mediana tranquila: tortugas, snorkel, bici, mar y calma.',waze:'https://waze.com/ul?ll=-8.3517,116.0584&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Gili%20Meno'},
  {name:'Uluwatu',x:78,y:68,coords:[-8.8291,115.0849],days:'Días 11-13',cost:'95-260 €/noche',img:IMG.sunset,text:'Acantilados, Padang Padang, templo, Kecak, surf suave y beach clubs.',waze:'https://waze.com/ul?ll=-8.8291,115.0849&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Uluwatu%20Bali'},
  {name:'Padang Padang',x:70,y:76,coords:[-8.8107,115.1024],days:'Día 12',cost:'1-3 € entrada orientativa',img:IMG.beach,text:'Playa icónica pequeña: ir temprano o al final del día.',waze:'https://waze.com/ul?ll=-8.8107,115.1024&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Padang%20Padang%20Beach%20Bali'},
  {name:'Villa final',x:57,y:34,coords:[-8.267,115.066],days:'Días 14-16',cost:'180-480 €/noche villa',img:IMG.villa,text:'Cierre premium: piscina privada, vegetación, masaje y cena final.',waze:'https://waze.com/ul?ll=-8.267,115.066&navigate=yes',gm:'https://www.google.com/maps/search/?api=1&query=Munduk%20Bali%20private%20pool%20villa'}
];

const guidePages=[
  {n:'01',title:'Portada',img:IMG.temple,body:'Indonesia 14-16 días. Bali, Gili Meno, Padang Padang y dos noches finales en villa tropical.',boxes:['Reserva primero: vuelos, Gili Meno, villa final y ferry.','Evita: días cargados después del ferry y traslados largos antes del vuelo.']},
  {n:'02',title:'Ruta principal',img:IMG.rice,body:'La ruta empieza en Ubud para entrar en selva y arrozales, cruza a Gili Meno para mar tranquilo, baja a Uluwatu para playa y termina con dos noches de villa.',boxes:['4 bases máximas para no romper el viaje.','Día colchón en Gili para cubrir mar o cansancio.']},
  {n:'03',title:'Alojamientos',img:IMG.villa,body:'Hoteles con misión concreta: Ubud visual, Gili en playa, Uluwatu práctico y villa final de impacto.',boxes:['Ubud: piscina y buena ubicación.','Villa final: piscina privada, vegetación y cena especial.']},
  {n:'04',title:'Experiencias',img:IMG.snorkel,body:'Snorkel con tortugas, Padang Padang temprano, Kecak en Uluwatu, cascadas, arrozales, surf suave y beach club.',boxes:['Prioridad: Gili Meno snorkel.','Plan social: beach club/surf para Iria e Izan.']},
  {n:'05',title:'Comidas',img:IMG.food,body:'Comidas ligeras en días de traslado. Cenas visuales en Ubud, isla y Uluwatu. Cena final dentro del hotel para evitar logística.',boxes:['Ferry day: comida simple.','Último día: cena sin desplazamientos.']},
  {n:'06',title:'Transportes',img:IMG.beach,body:'Coche privado en Bali, ferry rápido a Gili Meno, caminar o bici en isla y Waze/Google Maps para cada tramo.',boxes:['Waze: precargar ruta con conexión.','Offline: llevar mapa de Bali/Indonesia descargado de respaldo.']}
];

const itinerary=[
 {d:'1',zone:'Denpasar',title:'Llegada y primera noche sin presión',img:IMG.plane,hotel:'Ubud boutique o hotel aeropuerto si se llega tarde · 75-160 €/noche',breakfast:'Vuelo',lunch:'Comida ligera al llegar',dinner:'Cena sencilla cerca del hotel · 10-18 € p/p',morning:'Vuelo internacional y llegada.',afternoon:'Traslado privado y check-in.',night:'Descanso, eSIM, efectivo y agua.',transport:'Aeropuerto-Ubud 1h15-2h · 18-35 € coche',cost:'55-120 € + hotel',links:['Denpasar','Ubud']},
 {d:'2',zone:'Ubud',title:'Arrozales, piscina y primera cena bonita',img:IMG.rice,hotel:'Ubud con piscina · 75-180 €/noche',breakfast:'Desayuno hotel',lunch:'Warung arrozales · 8-16 € p/p',dinner:'Restaurante jardín Ubud · 18-35 € p/p',morning:'Tegallalang o Campuhan temprano.',afternoon:'Piscina, masaje y paseo centro.',night:'Cena visual sin traslados largos.',transport:'Taxi local o conductor medio día · 25-45 €',cost:'65-150 € p/p según spa',links:['Ubud','Tegallalang Rice Terrace']},
 {d:'3',zone:'Ubud',title:'Templos, agua sagrada y mercado',img:IMG.temple,hotel:'Mismo hotel Ubud',breakfast:'Hotel',lunch:'Ubud centro · 8-18 € p/p',dinner:'Cena familiar · 15-30 € p/p',morning:'Tirta Empul o Goa Gajah.',afternoon:'Mercado, café y taller opcional.',night:'Noche suave.',transport:'Conductor 6h · 45-70 € grupo',cost:'70-140 € p/p',links:['Tirta Empul Temple','Ubud Market']},
 {d:'4',zone:'Ubud',title:'Cascadas y aventura suave',img:IMG.waterfall,hotel:'Mismo hotel Ubud',breakfast:'Hotel',lunch:'Comida cerca de cascada · 8-15 €',dinner:'Libre en Ubud',morning:'Tibumana o Kanto Lampo temprano.',afternoon:'Quad suave, café o spa.',night:'Cena cerca del alojamiento.',transport:'Coche privado día · 55-80 € grupo',cost:'75-160 € p/p',links:['Tibumana Waterfall','Kanto Lampo Waterfall']},
 {d:'5',zone:'Ubud',title:'Día flexible para pareja e hijos',img:IMG.rice,hotel:'Mismo hotel Ubud',breakfast:'Hotel',lunch:'Café bonito · 10-18 €',dinner:'Cena especial Ubud · 20-40 €',morning:'Monkey Forest o descanso.',afternoon:'Compras, piscina, masaje.',night:'Cena y preparar salida.',transport:'A pie + taxis cortos',cost:'45-120 € p/p',links:['Ubud Monkey Forest','Campuhan Ridge Walk']},
 {d:'6',zone:'Sidemen',title:'Valle real antes del mar',img:IMG.rice,hotel:'Sidemen eco lodge · 90-220 €/noche o última noche Ubud',breakfast:'Hotel',lunch:'Valle de Sidemen · 10-18 €',dinner:'Cena con vistas · 18-35 €',morning:'Ruta escénica desde Ubud.',afternoon:'Arrozales y mirador Agung.',night:'Dormir Sidemen o volver a Ubud.',transport:'Coche privado · 55-85 € grupo',cost:'80-170 € p/p',links:['Sidemen Bali']},
 {d:'7',zone:'Gili Meno',title:'Ferry y entrada en isla tranquila',img:IMG.snorkel,hotel:'Gili Meno playa · 80-210 €/noche',breakfast:'Salida temprana',lunch:'Comida al llegar · 8-16 €',dinner:'Cena frente al mar · 15-30 €',morning:'Coche a puerto Padang Bai/Sanur.',afternoon:'Ferry rápido y check-in.',night:'Playa y cena tranquila.',transport:'Coche + ferry 35-65 € p/p',cost:'90-180 € p/p + hotel',links:['Padang Bai Harbour','Gili Meno']},
 {d:'8',zone:'Gili Meno',title:'Snorkel con tortugas',img:IMG.snorkel,hotel:'Mismo hotel Gili Meno',breakfast:'Hotel',lunch:'Chiringuito playa · 8-16 €',dinner:'Cena isla · 15-30 €',morning:'Snorkel: tortugas y esculturas.',afternoon:'Bici o descanso.',night:'Atardecer sin ruido.',transport:'Barca local + bici',cost:'45-110 € p/p',links:['Gili Meno Turtle Point']},
 {d:'9',zone:'Gili Meno',title:'Día isla sin reloj',img:IMG.beach,hotel:'Mismo hotel Gili Meno',breakfast:'Hotel',lunch:'Playa · 8-16 €',dinner:'Cena especial de isla · 18-35 €',morning:'Paseo vuelta a la isla.',afternoon:'Kayak, paddle o hamacas.',night:'Cena mirando a Lombok.',transport:'Bici/caminar/cidomo',cost:'40-120 € p/p',links:['Gili Meno Island']},
 {d:'10',zone:'Gili Meno',title:'Colchón de mar y fotos',img:IMG.snorkel,hotel:'Mismo hotel Gili Meno',breakfast:'Hotel',lunch:'Comida junto al agua',dinner:'Última noche de isla',morning:'Snorkel suave o playa norte.',afternoon:'Libre para cada uno.',night:'Cierre de isla.',transport:'Sin coche',cost:'35-90 € p/p',links:['Gili Meno']},
 {d:'11',zone:'Uluwatu',title:'Vuelta a Bali y acantilados',img:IMG.sunset,hotel:'Uluwatu/Bingin · 95-260 €/noche',breakfast:'Hotel + ferry',lunch:'En ruta o Uluwatu',dinner:'Cena con vistas · 20-45 €',morning:'Barco de regreso.',afternoon:'Traslado a Uluwatu y descanso.',night:'Sunset y cena.',transport:'Ferry + coche 70-150 € grupo + ferry',cost:'90-190 € p/p + hotel',links:['Gili Meno to Uluwatu']},
 {d:'12',zone:'Padang Padang',title:'Playa, surf y beach club',img:IMG.beach,hotel:'Mismo hotel Uluwatu',breakfast:'Hotel',lunch:'Bingin café · 12-25 €',dinner:'Beach club/cena · 35-120 €',morning:'Padang Padang temprano.',afternoon:'Surf suave o beach club.',night:'Atardecer acantilado.',transport:'Taxi local/conductor',cost:'55-160 € p/p',links:['Padang Padang Beach Bali','Bingin Beach']},
 {d:'13',zone:'Uluwatu',title:'Templo y Kecak al atardecer',img:IMG.temple,hotel:'Mismo hotel Uluwatu',breakfast:'Hotel',lunch:'Comida ligera',dinner:'Cena final sur · 25-55 €',morning:'Piscina o playa suave.',afternoon:'Templo Uluwatu + Kecak 18:00.',night:'Cena especial.',transport:'Taxi/conductor local',cost:'60-140 € p/p',links:['Uluwatu Temple']},
 {d:'14',zone:'Villa final',title:'Check-in en hotel wow',img:IMG.villa,hotel:'Villa tropical piscina privada · 180-480 €/noche',breakfast:'Hotel Uluwatu',lunch:'Comida en ruta o hotel',dinner:'Cena romántica hotel · 35-90 €',morning:'Traslado sin madrugar.',afternoon:'Piscina privada, fotos, descanso.',night:'Cena en la villa.',transport:'Uluwatu-villa 2h30-3h30 · 55-90 € coche',cost:'120-250 € p/p + villa',links:['Munduk Bali private pool villa']},
 {d:'15',zone:'Villa final',title:'Spa, cascada suave y cierre',img:IMG.villa,hotel:'Misma villa final',breakfast:'Desayuno largo',lunch:'Hotel o mirador · 15-30 €',dinner:'Cena final · 40-100 €',morning:'Masaje y piscina.',afternoon:'Cascada cercana o sesión de fotos.',night:'Brindis final.',transport:'Coche corto opcional',cost:'90-230 € p/p',links:['Munduk waterfalls Bali']},
 {d:'16',zone:'Salida',title:'Margen real antes del vuelo',img:IMG.plane,hotel:'Salida',breakfast:'Hotel',lunch:'Cerca de ruta al aeropuerto',dinner:'Vuelo o aeropuerto',morning:'Check-out y salida con margen.',afternoon:'Traslado al aeropuerto.',night:'Vuelo de regreso.',transport:'Villa-aeropuerto 2h30-4h · 45-85 € coche',cost:'70-140 € p/p',links:['Munduk to Ngurah Rai International Airport']}
];

const reserves={
 hotels:[
  {title:'Ubud boutique con piscina',img:IMG.rice,price:'75-180 €/noche',text:'Base para días 2-5. Prioridad: piscina, desayuno, buen acceso y no demasiado lejos del centro.',links:['https://www.booking.com/searchresults.es.html?ss=Ubud%20Bali','https://www.tripadvisor.es/Search?q=Ubud%20Bali%20hotel']},
  {title:'Gili Meno frente al mar',img:IMG.snorkel,price:'80-210 €/noche',text:'Reservar pronto. La isla tiene menos oferta y agosto se llena.',links:['https://www.booking.com/searchresults.es.html?ss=Gili%20Meno','https://www.tripadvisor.es/Search?q=Gili%20Meno%20hotel']},
  {title:'Uluwatu / Bingin práctico',img:IMG.sunset,price:'95-260 €/noche',text:'Base para Padang Padang, Kecak, surf suave y beach club.',links:['https://www.booking.com/searchresults.es.html?ss=Uluwatu%20Bali','https://www.tripadvisor.es/Search?q=Uluwatu%20hotel']},
  {title:'Villa final con piscina privada',img:IMG.villa,price:'180-480 €/noche',text:'Dos noches finales. Prioridad real del viaje visual.',links:['https://www.booking.com/searchresults.es.html?ss=Munduk%20Bali%20private%20pool%20villa','https://www.google.com/search?q=Bali+private+pool+villa+Munduk+Ubud']}
 ],
 flights:[
  {title:'Ventana 10-26 agosto',img:IMG.plane,price:'comparar',text:'Mirar Madrid y Barcelona a Denpasar. Descartar escalas muy largas.',links:['https://www.skyscanner.es/transporte/vuelos/es/dps/','https://www.google.com/travel/flights?q=Madrid%20to%20Denpasar%20August']},
  {title:'Ventana 14-29 agosto',img:IMG.plane,price:'comparar',text:'Buena candidata para 16 días completos.',links:['https://www.trip.com/flights/','https://www.edreams.es/vuelos/']},
  {title:'Ventana 18 agosto-1 septiembre',img:IMG.plane,price:'comparar',text:'Puede abaratar vuelo y mantener ruta.',links:['https://www.skyscanner.es/','https://www.wego.com/flights']}
 ],
 activities:[
  {title:'Snorkel Gili Meno',img:IMG.snorkel,price:'18-45 € p/p',text:'Tortugas, estatuas submarinas y barca local.',links:['https://www.viator.com/searchResults/all?text=Gili%20Meno%20snorkeling','https://www.klook.com/search/result/?query=Gili%20Meno%20snorkeling']},
  {title:'Uluwatu Kecak',img:IMG.temple,price:'13-18 € p/p orientativo',text:'Templo y espectáculo de tarde. Mejor reservar con margen.',links:['https://www.klook.com/search/result/?query=Uluwatu%20Kecak','https://www.viator.com/searchResults/all?text=Uluwatu%20Kecak']},
  {title:'Surf / beach club Uluwatu',img:IMG.beach,price:'25-120 € p/p',text:'Plan molón para Iria e Izan y para hacerlo en grupo.',links:['https://www.google.com/search?q=Padang+Padang+surf+lesson+Bali','https://www.google.com/search?q=Uluwatu+beach+club+reservation']},
  {title:'Spa y cena final',img:IMG.villa,price:'60-160 € p/p',text:'Cierre de viaje: masaje, piscina privada y cena sin moverse.',links:['https://www.google.com/search?q=Bali+private+villa+spa+dinner+Munduk']}
 ],
 food:[
  {title:'Ubud: cena jardín',img:IMG.food,price:'18-35 € p/p',text:'Cena visual sin coche largo después de templos o cascadas.',links:['https://www.google.com/maps/search/Ubud+romantic+restaurant']},
  {title:'Gili Meno: cena playa',img:IMG.beach,price:'15-30 € p/p',text:'Mesa sencilla frente al mar. Mejor que plan caro con traslado.',links:['https://www.google.com/maps/search/Gili+Meno+beach+restaurant']},
  {title:'Uluwatu: atardecer',img:IMG.sunset,price:'25-55 € p/p',text:'Cena tras Kecak o después de Padang Padang.',links:['https://www.google.com/maps/search/Uluwatu+sunset+restaurant']},
  {title:'Villa final: cena privada',img:IMG.villa,price:'40-100 € p/p',text:'Última noche sin taxis ni prisa.',links:['https://www.google.com/search?q=Bali+villa+private+dinner+Ubud+Munduk']}
 ]
};

function $(s,r=document){return r.querySelector(s)} function $all(s,r=document){return [...r.querySelectorAll(s)]}
function bg(url){return `style="--img:url('${url}')"`} function mapUrl(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function routeUrl(q){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`}
function loadIdeas(){try{return JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{return[]}} function saveIdeas(v){localStorage.setItem(storageKey,JSON.stringify(v))}
function appliedIdeas(day){return loadIdeas().filter(i=>i.applied && (String(i.day||'').includes(day)||!i.day))}

function render(){renderCover();renderGuide();renderMap();renderItinerary();renderBookings();renderKids();renderFinal();bindPageButtons();renderDots();show(0)}
function renderCover(){
 $('#screen-cover').innerHTML=`<div class="cover-layout"><div class="cover-photo" ${bg(IMG.temple)}><span class="kicker">Travel guide</span><h1>Indonesia 14-16 días</h1><p class="lead">Bali, Gili Meno, Padang Padang y dos noches finales en villa tropical con piscina privada.</p><div class="chips"><span class="chip y">Pareja + Iria + Izan</span><span class="chip">Agosto</span><span class="chip c">Ruta sin paliza</span></div></div><div class="panel"><div class="panel-pad"><span class="kicker">Resumen ejecutivo</span><h2>Viaje visual, paginado y reservable</h2><div class="cover-mini"><div class="mini-img" ${bg(IMG.rice)}>Ubud</div><div class="mini-img" ${bg(IMG.snorkel)}>Gili Meno</div><div class="mini-img" ${bg(IMG.beach)}>Padang Padang</div><div class="mini-img" ${bg(IMG.villa)}>Villa final</div></div><div class="warning"><div><strong>Reserva primero</strong><p>Vuelos, Gili Meno, villa final y ferry rápido.</p></div><div><strong>Evita</strong><p>Traslados largos antes del vuelo y planes fuertes tras ferry.</p></div></div><div class="chips"><button class="btn fire" data-go="guide">Abrir guía</button><button class="btn" data-go="map">Ver mapa 3D</button><button class="btn alt" data-go="kids">Iria & Izan</button></div></div></div></div>`;
}
function renderGuide(){
 const a=guidePages[guideIndex], b=guidePages[(guideIndex+1)%guidePages.length];
 $('#screen-guide').innerHTML=`<div class="book-shell"><aside class="thumbs">${guidePages.map((p,i)=>`<button class="thumb ${i===guideIndex?'active':''}" data-guide="${i}" ${bg(p.img)}><span>${p.n}<br>${p.title}</span></button>`).join('')}</aside><div class="magazine"><article class="mag-page"><span class="page-no">${a.n}</span><div class="mag-hero" ${bg(a.img)}></div><div class="mag-content"><span class="kicker">Guidebook</span><h2 class="mag-title">${a.title}</h2><p>${a.body}</p><div class="mag-cols">${a.boxes.map(x=>`<div class="mag-box">${x}</div>`).join('')}</div></div></article><article class="mag-page dark"><span class="page-no">${b.n}</span><div class="mag-hero" ${bg(b.img)}></div><div class="mag-content"><span class="kicker">Indonesia</span><h2 class="mag-title">${b.title}</h2><p>${b.body}</p><div class="mag-cols">${b.boxes.map(x=>`<div class="mag-box">${x}</div>`).join('')}</div></div></article><div class="book-actions"><button class="btn alt" id="prevGuide">Página anterior</button><button class="btn" id="nextGuide">Página siguiente</button></div></div></div>`;
 $all('[data-guide]').forEach(b=>b.onclick=()=>{guideIndex=+b.dataset.guide;renderGuide()}); $('#prevGuide').onclick=()=>{guideIndex=(guideIndex-1+guidePages.length)%guidePages.length;renderGuide()}; $('#nextGuide').onclick=()=>{guideIndex=(guideIndex+1)%guidePages.length;renderGuide()};
}
function renderMap(){
 const p=points[mapIndex];
 $('#screen-map').innerHTML=`<div class="map-grid" id="mapMode"><div class="iso-map-wrap"><img class="iso-map" src="assets/img/indonesia_isometric_map.png" alt="Mapa guía 3D de Indonesia">${points.map((pt,i)=>`<button class="map-pin ${i===mapIndex?'active':''}" data-map="${i}" style="left:${pt.x}%;top:${pt.y}%">${pt.name}</button>`).join('')}</div><div id="gpsMap" class="gps-map"></div><aside class="panel"><div class="panel-pad"><span class="kicker">${p.days}</span><h2>${p.name}</h2><div class="map-detail-img" ${bg(p.img)}></div><p>${p.text}</p><div class="chips"><span class="chip y">${p.cost}</span><span class="chip c">${p.days}</span></div><div class="chips"><a class="btn" href="${p.waze}" target="_blank">Abrir en Waze</a><a class="btn alt" href="${p.gm}" target="_blank">Google Maps</a><button class="btn fire" id="toggleRealMap">GPS real</button></div><div class="mag-box"><b>Modo offline</b><p>Precarga cada ruta en Waze con conexión antes de salir. Lleva además Bali/Indonesia descargado en Google Maps, CoMaps, Magic Earth u otra app offline para respaldo sin datos.</p></div><div class="map-list">${points.map((pt,i)=>`<button class="${i===mapIndex?'active':''}" data-map="${i}"><b>${pt.name}</b><br>${pt.days} · ${pt.cost}</button>`).join('')}</div></div></aside></div>`;
 $all('[data-map]').forEach(btn=>btn.onclick=()=>{mapIndex=+btn.dataset.map;renderMap()}); $('#toggleRealMap').onclick=()=>toggleRealMap();
}
function toggleRealMap(){
 const mode=$('#mapMode'); mode.classList.toggle('map-mode'); mode.classList.toggle('real');
 if(mode.classList.contains('real')) setTimeout(initLeaflet,50);
}
function initLeaflet(){
 if(!window.L) return; if(map){map.remove();map=null}
 map=L.map('gpsMap',{scrollWheelZoom:true}).setView(points[mapIndex].coords,8);
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);
 const coords=points.map(p=>p.coords); L.polyline(coords,{color:'#ffd400',weight:5,dashArray:'10 8'}).addTo(map);
 points.forEach((p,i)=>L.marker(p.coords).addTo(map).bindPopup(`<b>${p.name}</b><br>${p.days}<br>${p.cost}`).on('click',()=>{mapIndex=i;renderMap();setTimeout(toggleRealMap,60)}));
 map.fitBounds(L.latLngBounds(coords).pad(.2));
}
function renderItinerary(){
 const d=itinerary[dayIndex], ideas=appliedIdeas(d.d);
 $('#screen-itinerary').innerHTML=`<div class="day-layout"><aside class="day-list">${itinerary.map((x,i)=>`<button class="${i===dayIndex?'active':''}" data-day="${i}">Día ${x.d}<br><span>${x.zone}</span></button>`).join('')}</aside><div class="panel"><div class="panel-pad"><div class="day-main"><div class="day-photo" ${bg(d.img)}><span class="kicker">Día ${d.d} · ${d.zone}</span><h2>${d.title}</h2></div><div class="scroll"><div class="schedule"><div class="schedule-card"><b>Mañana</b>${d.morning}</div><div class="schedule-card"><b>Comida</b>${d.lunch}</div><div class="schedule-card"><b>Tarde</b>${d.afternoon}</div><div class="schedule-card"><b>Noche</b>${d.night}</div></div><div class="detail-grid"><div class="detail-card"><b>Hotel</b>${d.hotel}</div><div class="detail-card"><b>Transporte</b>${d.transport}</div><div class="detail-card"><b>Comidas</b>${d.breakfast}<br>${d.dinner}</div><div class="detail-card"><b>Coste día</b>${d.cost}</div></div>${ideas.length?`<div class="applied-ideas"><b>Ideas aplicadas de Iria & Izan</b><p>${ideas.map(i=>`${i.author}: ${i.title}`).join('<br>')}</p></div>`:''}<div class="chips" style="margin-top:12px">${d.links.map(l=>`<a class="btn alt" href="${routeUrl(l)}" target="_blank">Ruta: ${l}</a>`).join('')}<button class="btn" id="nextDay">Siguiente día</button></div></div></div></div></div></div>`;
 $all('[data-day]').forEach(b=>b.onclick=()=>{dayIndex=+b.dataset.day;renderItinerary()}); $('#nextDay').onclick=()=>{dayIndex=(dayIndex+1)%itinerary.length;renderItinerary()};
}
function renderBookings(){
 const list=reserves[reserveTab];
 $('#screen-bookings').innerHTML=`<div class="panel"><div class="panel-pad"><span class="kicker">Reservas</span><h2>Hoteles, vuelos, actividades y comidas</h2><div class="reserve-nav">${Object.keys(reserves).map(k=>`<button class="${k===reserveTab?'active':''}" data-reserve="${k}">${k==='hotels'?'Hoteles':k==='flights'?'Vuelos':k==='activities'?'Actividades':'Comidas'}</button>`).join('')}</div><div class="card-grid scroll">${list.map(r=>`<article class="travel-card"><div class="travel-img" ${bg(r.img)}></div><div class="travel-body"><h3>${r.title}</h3><div class="price">${r.price}</div><p>${r.text}</p><div class="chips">${r.links.map((l,i)=>`<a class="btn ${i?'alt':''}" href="${l}" target="_blank">Abrir ${i?2:1}</a>`).join('')}</div></div></article>`).join('')}</div></div></div>`;
 $all('[data-reserve]').forEach(b=>b.onclick=()=>{reserveTab=b.dataset.reserve;renderBookings()});
}
function renderKids(){
 const ideas=loadIdeas();
 $('#screen-kids').innerHTML=`<div class="kids-grid"><div class="panel"><div class="panel-pad"><span class="kicker">Iria & Izan</span><h2>Subir ideas al viaje</h2><form class="kids-form" id="ideaForm"><input id="ideaTitle" placeholder="Nombre: hotel, playa, reel, restaurante..."><select id="ideaAuthor"><option>Iria</option><option>Izan</option><option>Aitor</option></select><select id="ideaType"><option>Actividad</option><option>Hotel</option><option>Restaurante</option><option>Playa</option><option>Reel/Instagram/TikTok</option><option>Documento</option></select><select id="ideaDay"><option value="">Sin día fijo</option>${itinerary.map(d=>`<option value="${d.d}">Día ${d.d} · ${d.zone}</option>`).join('')}</select><input id="ideaLink" placeholder="Enlace IG/TikTok/hotel/web"><input type="file" id="ideaFile" accept="image/*,.pdf,.doc,.docx" multiple><textarea id="ideaNotes" rows="4" placeholder="Por qué encaja, precio visto, zona, detalle..."></textarea><button class="btn fire">Guardar idea</button></form></div></div><div class="panel"><div class="panel-pad"><span class="kicker">Bandeja de ideas</span><h2>Seleccionar y aplicar al viaje</h2><div class="ideas-grid scroll">${ideas.length?ideas.map((i,idx)=>ideaCard(i,idx)).join(''):'<p class="lead">Aún no hay ideas. Subid enlaces, hoteles, fotos o notas y luego marcad “Aplicar al viaje”.</p>'}</div></div></div></div>`;
 $('#ideaForm').onsubmit=saveIdea; $all('[data-apply]').forEach(b=>b.onclick=()=>toggleIdea(+b.dataset.apply)); $all('[data-delete]').forEach(b=>b.onclick=()=>deleteIdea(+b.dataset.delete));
}
function ideaCard(i,idx){return `<article class="idea ${i.applied?'applied':''}">${i.preview?`<div class="idea-img" style="background-image:url('${i.preview}')"></div>`:''}<h3>${i.title}</h3><div class="chips"><span class="chip y">${i.author}</span><span class="chip c">${i.type}</span>${i.day?`<span class="chip">Día ${i.day}</span>`:''}</div><p>${i.notes||'Sin notas.'}</p>${i.link?`<a class="btn alt" href="${i.link}" target="_blank">Abrir enlace</a>`:''}${i.files?.length?`<span class="file-chip">${i.files.length} archivo(s) guardados</span>`:''}<div class="chips"><button class="btn" data-apply="${idx}">${i.applied?'Quitar del viaje':'Aplicar al viaje'}</button><button class="btn fire" data-delete="${idx}">Borrar</button></div></article>`}
function saveIdea(e){
 e.preventDefault(); const title=$('#ideaTitle').value.trim(); if(!title) return toast('Falta nombre de la idea');
 const files=[...$('#ideaFile').files]; const idea={title,author:$('#ideaAuthor').value,type:$('#ideaType').value,day:$('#ideaDay').value,link:$('#ideaLink').value.trim(),notes:$('#ideaNotes').value.trim(),applied:false,files:[],preview:''};
 if(!files.length){const arr=loadIdeas(); arr.unshift(idea); saveIdeas(arr); renderKids(); return toast('Idea guardada')}
 let pending=files.length; files.slice(0,4).forEach(f=>{const r=new FileReader(); r.onload=()=>{idea.files.push({name:f.name,type:f.type,data:r.result}); if(!idea.preview && f.type.startsWith('image/')) idea.preview=r.result; if(--pending===0){const arr=loadIdeas(); arr.unshift(idea); saveIdeas(arr); renderKids(); toast('Idea guardada')}}; r.readAsDataURL(f)});
}
function toggleIdea(idx){const arr=loadIdeas(); arr[idx].applied=!arr[idx].applied; saveIdeas(arr); renderKids(); renderItinerary(); renderFinal(); toast(arr[idx].applied?'Idea aplicada al viaje':'Idea quitada del viaje')}
function deleteIdea(idx){const arr=loadIdeas(); arr.splice(idx,1); saveIdeas(arr); renderKids(); renderItinerary(); renderFinal()}
function renderFinal(){
 const applied=loadIdeas().filter(i=>i.applied);
 $('#screen-final').innerHTML=`<div class="final-grid"><div class="reco"><div><span class="kicker" style="color:#06120c">Recomendación final</span><h2>Opción equilibrada de 16 días</h2><p>Ubud + Sidemen + Gili Meno + Uluwatu + dos noches finales en villa tropical.</p></div><div class="chips"><button class="btn alt" onclick="window.print()">Guardar PDF</button><button class="btn" id="downloadSummary">Descargar resumen</button></div></div><div class="panel"><div class="panel-pad"><span class="kicker">Resumen final</span><h2>Qué reservar primero</h2><div class="final-cards scroll"><div class="final-card"><b>1. Vuelos</b><p>Comparar 3 ventanas de agosto y descartar escalas absurdas.</p></div><div class="final-card"><b>2. Gili Meno</b><p>Pocas plazas y menos oferta: bloquear hotel y ferry.</p></div><div class="final-card"><b>3. Villa final</b><p>Dos noches finales con piscina privada y cena especial.</p></div><div class="final-card"><b>4. Uluwatu</b><p>Base para Padang Padang, Kecak y beach club/surf.</p></div><div class="final-card"><b>Ideas aplicadas</b><p>${applied.length?applied.map(i=>`${i.author}: ${i.title}`).join('<br>'):'Sin ideas aplicadas todavía.'}</p></div><div class="final-card"><b>Importante</b><p>Precios y horarios orientativos: confirmar en proveedor antes de pagar.</p></div></div></div></div></div>`;
 $('#downloadSummary').onclick=downloadSummary;
}
function downloadSummary(){const applied=loadIdeas().filter(i=>i.applied).map(i=>`${i.author}: ${i.title}`).join('\n')||'Sin ideas aplicadas';const text=`NUSA TRAVEL OS · RESUMEN FINAL\n\nRuta: Ubud + Sidemen + Gili Meno + Uluwatu + villa final\nDuración: 14-16 días en agosto\nReserva primero: vuelos, Gili Meno, villa final y ferry\n\nIdeas Iria & Izan:\n${applied}`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nusa-travel-os-resumen-v7.txt';a.click();URL.revokeObjectURL(a.href)}
function bindPageButtons(){$all('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(id){show(screens.indexOf(id))} function show(i){if(i<0||i>=screens.length)return;current=i;$all('.screen').forEach(s=>s.classList.remove('active'));$(`#screen-${screens[i]}`).classList.add('active');$all('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===screens[i]));renderDots(); if(screens[i]==='map'&&$('#mapMode')?.classList.contains('real'))setTimeout(initLeaflet,50)}
function renderDots(){ $('#dots').innerHTML=screens.map((s,i)=>`<button class="dot ${i===current?'active':''}" data-dot="${i}" aria-label="${s}"></button>`).join('');$all('[data-dot]').forEach(d=>d.onclick=()=>show(+d.dataset.dot)) }
function toast(t){const el=document.createElement('div');el.textContent=t;el.style.cssText='position:fixed;left:50%;bottom:86px;transform:translateX(-50%);z-index:999;background:linear-gradient(135deg,#00d976,#00d5ff);color:#04120c;padding:13px 18px;border-radius:999px;font-weight:900;box-shadow:0 18px 40px rgba(0,0,0,.45)';document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function startAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),master=ctx.createGain();master.gain.value=.18;master.connect(ctx.destination);const buf=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.2;const noise=ctx.createBufferSource();noise.buffer=buf;noise.loop=true;const low=ctx.createBiquadFilter();low.type='lowpass';low.frequency.value=780;noise.connect(low).connect(master);noise.start();const intervals=[setInterval(()=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=900+Math.random()*1600;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(.055,ctx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.45);o.connect(g).connect(master);o.start();o.stop(ctx.currentTime+.5)},1200)];audio={ctx,noise,intervals};$('#jungleBtn').classList.add('playing')}
function stopAudio(){if(!audio)return;audio.intervals.forEach(clearInterval);try{audio.noise.stop();audio.ctx.close()}catch{}audio=null;$('#jungleBtn').classList.remove('playing')}
function init(){render();$('#prevBtn').onclick=()=>show(current-1);$('#nextBtn').onclick=()=>show(current+1);$('#jungleBtn').onclick=()=>audio?stopAudio():startAudio();document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1)}); if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
