'use strict';
const IMG={hero:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1800&q=88',rice:'https://images.unsplash.com/photo-1559628233-100c798642d4?auto=format&fit=crop&w=1600&q=88',temple:'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1600&q=88',beach:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=88',villa:'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=88',snorkel:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=88',waterfall:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=88',plane:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=88',food:'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1600&q=88'};
const screens=['home','guide','map','days','bookings','ideas','final']; let current=0, guidePage=0, dayIndex=0, mapMode='guide', mapIndex=0, soundOn=false, audio=null;
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const waze=(lat,lng)=>`https://waze.com/ul?ll=${lat},${lng}&navigate=yes`; const gmaps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`; const route=q=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`;
const guidePages=[
 {title:'Portada',sub:'Indonesia 14-16 días',img:IMG.hero,text:'Bali, Gili Meno, Padang Padang y dos noches finales en villa tropical con piscina privada.',chips:['Pareja + Iria + Izan','Agosto','Selva + playa','Ruta sin paliza'],photos:[['Ubud',IMG.rice],['Gili Meno',IMG.snorkel],['Padang Padang',IMG.beach],['Villa final',IMG.villa]]},
 {title:'Ruta recomendada',sub:'Interior · isla · sur · final wow',img:IMG.temple,text:'La secuencia evita retrocesos: primero Ubud y arrozales, después Gili Meno, luego Uluwatu/Padang Padang y cierre en hotel de impacto.',chips:['4 bases','1 ferry clave','1 día colchón','2 noches final'],photos:[['Arrozales',IMG.rice],['Templo',IMG.temple],['Ferry',IMG.beach],['Villa',IMG.villa]]},
 {title:'Alojamientos',sub:'Dónde dormir y por qué',img:IMG.villa,text:'El viaje funciona si cada hotel tiene una misión: Ubud para explorar, Gili para playa, Uluwatu para planes, final para descansar.',chips:['Ubud 4 noches','Gili Meno 3 noches','Uluwatu 3 noches','Villa 2 noches'],photos:[['Boutique Ubud',IMG.rice],['Playa Gili',IMG.snorkel],['Sur Bali',IMG.beach],['Final wow',IMG.villa]]},
 {title:'Actividades clave',sub:'Planes molones sin saturar',img:IMG.snorkel,text:'Snorkel con tortugas, Padang Padang temprano, Kecak en Uluwatu, cascadas, beach club y spa final.',chips:['Snorkel','Surf suave','Beach club','Spa final'],photos:[['Snorkel',IMG.snorkel],['Cascada',IMG.waterfall],['Padang',IMG.beach],['Cena',IMG.food]]},
 {title:'Reservas críticas',sub:'Orden correcto para cerrar el viaje',img:IMG.plane,text:'Primero vuelos, después villa final y Gili Meno. Luego Ubud/Uluwatu, ferries y actividades con cupo.',chips:['1 vuelos','2 Gili','3 villa final','4 ferries'],photos:[['Vuelo',IMG.plane],['Ferry',IMG.beach],['Hotel',IMG.villa],['Mapa',IMG.temple]]}
];
const places=[
 {name:'Denpasar Airport',short:'Denpasar',days:'Día 1 y salida',lat:-8.7467,lng:115.1668,img:IMG.plane,cost:'18-35 € traslado coche',text:'Entrada y salida internacional. Si se llega tarde, plan suave.',offline:'Abrir ruta con datos antes de salir y dejarla en recientes de Waze.'},
 {name:'Ubud',short:'Ubud',days:'Días 2-5',lat:-8.5069,lng:115.2625,img:IMG.rice,cost:'75-180 €/noche hotel boutique',text:'Base de arrozales, templos, cascadas, cafés y masaje.',offline:'Descargar zona Bali en app de mapas offline y guardar Ubud como favorito.'},
 {name:'Sidemen',short:'Sidemen',days:'Día 6',lat:-8.4667,lng:115.4333,img:IMG.waterfall,cost:'45-70 € coche privado día',text:'Valle más auténtico y visual antes del puerto.',offline:'Ruta Ubud-Sidemen-Padang Bai precargada.'},
 {name:'Padang Bai Harbour',short:'Padang Bai',days:'Día 7',lat:-8.5311,lng:115.5082,img:IMG.beach,cost:'35-65 € ferry p/p orientativo',text:'Puerto para barco rápido a Gili Meno.',offline:'Llegar con margen y llevar billete/foto del embarque offline.'},
 {name:'Gili Meno',short:'Gili Meno',days:'Días 7-10',lat:-8.3517,lng:116.0584,img:IMG.snorkel,cost:'80-210 €/noche hotel playa',text:'Isla tranquila, snorkel, tortugas y cero prisa.',offline:'Guardar alojamiento y punto de llegada; moverse a pie/bici/cidomo.'},
 {name:'Uluwatu',short:'Uluwatu',days:'Días 11-13',lat:-8.8291,lng:115.0849,img:IMG.temple,cost:'95-260 €/noche hotel sur',text:'Acantilados, templo, Kecak, beach clubs y surf suave.',offline:'Guardar hotel, templo y Padang Padang.'},
 {name:'Padang Padang Beach',short:'Padang Padang',days:'Día 12',lat:-8.8107,lng:115.1024,img:IMG.beach,cost:'1-3 € entrada orientativa',text:'Playa icónica. Mejor temprano.',offline:'Guardar parking/entrada. No depender de conexión dentro de la cala.'},
 {name:'Villa final Munduk/Ubud alto',short:'Villa final',days:'Días 14-16',lat:-8.267,lng:115.066,img:IMG.villa,cost:'180-480 €/noche villa privada',text:'Cierre con selva, piscina, masaje, cena y descanso.',offline:'Descargar ruta al aeropuerto antes de la última noche.'}
];
const days=[
 {d:'1',z:'Denpasar',t:'Llegada y aterrizaje suave',img:IMG.plane,h:'Según vuelo',m:'Llegada, visado/entrada, SIM/eSIM y traslado.',c:'Comida ligera cerca del hotel.',a:'Check-in, piscina y descanso.',n:'Cena fácil. Dormir pronto.',hotel:'Hotel cómodo cerca de Ubud o aeropuerto si se llega tarde · 60-140 €/noche',food:'Warung tranquilo o hotel · 8-20 € p/p',transport:'Aeropuerto-Ubud 1 h 15-2 h · 18-35 € coche',links:['Denpasar Airport','Ubud Bali hotel']},
 {d:'2',z:'Ubud',t:'Arrozales y primera postal de Bali',img:IMG.rice,h:'07:30-21:30',m:'Tegallalang o Campuhan temprano.',c:'Comida con vistas a arrozales.',a:'Piscina, masaje y paseo por Ubud.',n:'Cena bonita pero tranquila.',hotel:'Boutique Ubud con piscina · 75-180 €/noche',food:'Restaurante arrozales · 12-30 € p/p',transport:'Taxi/coche local · 10-35 €',links:['Tegallalang Rice Terrace','Campuhan Ridge Walk']},
 {d:'3',z:'Ubud',t:'Templo, agua sagrada y mercado',img:IMG.temple,h:'08:00-22:00',m:'Tirta Empul o Goa Gajah con guía local.',c:'Comida en Ubud centro.',a:'Mercado, taller de plata o cocina balinesa.',n:'Cena familiar y paseo corto.',hotel:'Mismo hotel Ubud',food:'Warung + cena · 18-45 € p/p',transport:'Coche medio día · 35-60 €',links:['Tirta Empul Temple','Ubud Art Market']},
 {d:'4',z:'Ubud',t:'Cascada y aventura suave',img:IMG.waterfall,h:'07:30-21:30',m:'Tibumana o Kanto Lampo temprano.',c:'Comida en ruta.',a:'Quad, bici o columpio según ganas.',n:'Noche libre en Ubud.',hotel:'Mismo hotel Ubud',food:'Comida local · 10-25 € p/p',transport:'Coche 6-8 h · 55-90 € grupo',links:['Tibumana Waterfall','Kanto Lampo Waterfall']},
 {d:'5',z:'Ubud',t:'Día flexible con margen para Iria e Izan',img:IMG.jungle,h:'09:30-22:00',m:'Spa, Monkey Forest o café bonito.',c:'Comida libre.',a:'Aplicar ideas seleccionadas del panel Iria & Izan.',n:'Cena final Ubud.',hotel:'Última noche Ubud',food:'Libre · 15-45 € p/p',transport:'A pie + taxis cortos',links:['Ubud Monkey Forest','Ubud cafes']},
 {d:'6',z:'Sidemen',t:'Valle auténtico antes de la isla',img:IMG.rice,h:'08:00-21:00',m:'Salida a Sidemen con paradas fotográficas.',c:'Comida con vistas al valle.',a:'Paseo rural o piscina.',n:'Dormir en Sidemen o Padang Bai.',hotel:'Eco lodge Sidemen · 90-220 €/noche',food:'Restaurante panorámico · 12-35 € p/p',transport:'Ubud-Sidemen 1 h 30-2 h · 45-70 € coche',links:['Sidemen Bali','Padang Bai Harbour']},
 {d:'7',z:'Gili Meno',t:'Barco a la isla mediana',img:IMG.snorkel,h:'06:30-21:00',m:'Traslado a Padang Bai/Sanur.',c:'Ferry rápido y llegada a Gili Meno.',a:'Check-in, playa y vuelta suave.',n:'Cena frente al mar.',hotel:'Hotel playa Gili Meno · 80-210 €/noche',food:'Playa · 10-30 € p/p',transport:'Coche + ferry · 35-65 € p/p ferry',links:['Padang Bai to Gili Meno','Gili Meno hotel']},
 {d:'8',z:'Gili Meno',t:'Snorkel con tortugas',img:IMG.snorkel,h:'08:30-21:30',m:'Snorkel: tortugas y esculturas submarinas.',c:'Comida de playa.',a:'Bici o descanso.',n:'Atardecer y cena tranquila.',hotel:'Mismo hotel Gili Meno',food:'Warung playa · 10-28 € p/p',transport:'Barca local + bici · 18-45 € p/p actividad',links:['Gili Meno Turtle Point','Gili Meno underwater statues']},
 {d:'9',z:'Gili Meno',t:'Día sin coche, sin ruido y con mar',img:IMG.beach,h:'Libre',m:'Playa norte o kayak.',c:'Comida junto al agua.',a:'Tiempo libre para pareja y chicos.',n:'Cena especial de isla.',hotel:'Mismo hotel Gili Meno',food:'Cena playa · 18-50 € p/p',transport:'Bici/caminar/cidomo',links:['Gili Meno Island','Gili Meno beach']},
 {d:'10',z:'Gili Meno',t:'Día colchón de isla',img:IMG.snorkel,h:'Libre',m:'Repetir snorkel o descanso.',c:'Comida sin desplazarse.',a:'Aplicar ideas seleccionadas.',n:'Última noche de isla.',hotel:'Última noche Gili Meno',food:'Libre · 15-40 € p/p',transport:'Sin traslados largos',links:['Gili Meno snorkel tour','Gili Meno restaurants']},
 {d:'11',z:'Uluwatu',t:'Regreso a Bali y acantilados',img:IMG.temple,h:'07:30-22:00',m:'Ferry de vuelta.',c:'Comida en ruta o llegada al sur.',a:'Check-in y primer sunset.',n:'Cena en Bingin/Uluwatu.',hotel:'Hotel Uluwatu/Bingin · 95-260 €/noche',food:'Cena acantilado · 20-60 € p/p',transport:'Ferry + coche 2-4 h · 70-150 € grupo + ferry',links:['Gili Meno to Uluwatu','Bingin Beach']},
 {d:'12',z:'Padang Padang',t:'Playa, surf suave y beach club',img:IMG.beach,h:'08:00-23:00',m:'Padang Padang temprano.',c:'Comida en Bingin o beach café.',a:'Surf suave o beach club.',n:'Atardecer en acantilado.',hotel:'Mismo hotel Uluwatu',food:'Beach café · 18-55 € p/p',transport:'Taxis cortos/conductor local',links:['Padang Padang Beach','Uluwatu beach club']},
 {d:'13',z:'Uluwatu',t:'Templo, Kecak y noche potente',img:IMG.temple,h:'16:00-22:30',m:'Mañana libre/piscina.',c:'Comida sin prisa.',a:'Templo de Uluwatu y Kecak al atardecer.',n:'Cena especial sur.',hotel:'Última noche Uluwatu',food:'Cena especial · 25-70 € p/p',transport:'Taxi/coche local',links:['Uluwatu Temple','Kecak Uluwatu']},
 {d:'14',z:'Villa final',t:'Check-in en hotel wow',img:IMG.villa,h:'10:00-22:00',m:'Traslado sin madrugar.',c:'Comida en ruta o hotel.',a:'Piscina privada, fotos y descanso.',n:'Cena romántica en hotel.',hotel:'Villa tropical piscina privada · 180-480 €/noche',food:'Hotel · 25-85 € p/p',transport:'Uluwatu-Munduk/Ubud alto 2,5-3,5 h · 55-90 €',links:['Munduk private pool villa','Ubud jungle villa']},
 {d:'15',z:'Villa final',t:'Masaje, cascada suave y cierre',img:IMG.jungle,h:'09:30-22:30',m:'Desayuno lento y masaje.',c:'Comida panorámica.',a:'Cascada cercana o sesión de fotos.',n:'Cena final.',hotel:'Misma villa final',food:'Cena final · 35-100 € p/p',transport:'Coche corto opcional',links:['Munduk waterfalls','Bali spa private pool villa']},
 {d:'16',z:'Salida',t:'Margen inteligente según vuelo',img:IMG.plane,h:'Según vuelo',m:'Desayuno y salida.',c:'Comida fácil en ruta.',a:'Traslado al aeropuerto con margen.',n:'Vuelo de regreso.',hotel:'Sin noche o noche extra según vuelo',food:'Comida ruta · 10-25 € p/p',transport:'Villa-aeropuerto 2,5-4 h · 45-85 €',links:['Munduk to Ngurah Rai Airport','Ngurah Rai International Airport']}
];
const bookings={vuelos:[['Vuelos Madrid/Barcelona-Denpasar',IMG.plane,'850-1.550 € p/p orientativo','Comparar 3 ventanas en agosto, equipaje incluido y escalas razonables.',['Skyscanner','Trip.com','eDreams','Wego'],'https://www.skyscanner.es/transporte/vuelos/es/dps/'],['Comodidad por duración total',IMG.plane,'+200-400 € p/p si mejora mucho','Evitar escalas absurdas aunque no sea el precio más bajo.',['Flight Network','FareFirst','HappyFares'],'https://www.google.com/travel/flights?q=Madrid%20Denpasar%20August']],hoteles:[['Ubud boutique',IMG.rice,'75-180 €/noche','Piscina, buena ubicación y salida fácil a excursiones.',['trivago','Tripadvisor','Direct Host'],gmaps('Ubud boutique hotel pool')],['Gili Meno playa',IMG.snorkel,'80-210 €/noche','Prioridad alta por poca oferta en agosto.',['Tripadvisor','HomeToGo','Book Direct'],gmaps('Gili Meno beachfront hotel')],['Villa final',IMG.villa,'180-480 €/noche','Dos noches finales con piscina privada y vegetación.',['Trip.com','trivago','Direct Host'],gmaps('Bali jungle villa private pool')]],actividades:[['Snorkel Gili Meno',IMG.snorkel,'18-45 € p/p','Tortugas, esculturas y coral.',['Klook','Viator','Tripadvisor'],'https://www.viator.com/searchResults/all?text=Gili%20Meno%20snorkeling'],['Kecak Uluwatu',IMG.temple,'13-18 € p/p orientativo','Templo y atardecer.',['Klook','Headout','Tripadvisor'],'https://www.klook.com/search/result/?query=uluwatu%20kecak'],['Surf suave / beach club',IMG.beach,'25-120 € p/p','Plan divertido para Iria e Izan.',['Viator','Klook','Headout'],'https://www.viator.com/searchResults/all?text=Uluwatu%20surf%20lesson']],transporte:[['Bali-Gili Meno ferry',IMG.beach,'35-65 € p/p trayecto','Barco de mañana y operador bien valorado.',['12Go','Rome2Rio'], 'https://12go.asia/'],['Coche privado Bali',IMG.temple,'45-90 € día','Para rutas Ubud, Sidemen, Uluwatu y aeropuerto.',['Rome2Rio','Google Maps'],gmaps('Bali private driver')],['Waze + offline',IMG.temple,'Preparar antes de salir','Guardar rutas en Waze con conexión y descargar Indonesia/Bali en app offline.',['Waze','OsmAnd','Google Maps'],waze(-8.5069,115.2625)]]};
function card([title,img,price,text,apps,link]){return `<article class="card"><div class="card-img" style="--img:url('${img}')"></div><div class="card-body"><h3>${title}</h3><div class="price">${price}</div><p>${text}</p><div>${apps.map(a=>`<span class="chip blue">${a}</span>`).join('')}</div><div class="links"><a href="${link}" target="_blank">Abrir</a></div></div></article>`}
function renderHome(){qs('#home').innerHTML=`<div class="grid"><div class="panel pad"><span class="kicker">App de viaje · no guía en scroll</span><h1>Indonesia visual, paginada y accionable.</h1><p class="lead">Guía estilo revista, mapa tipo isla 3D, GPS/Waze, itinerario con hoteles, comidas, transportes, precios orientativos y zona para que Iria e Izan suban ideas.</p><div class="cta"><button class="primary" data-go="guide">Abrir guía</button><button class="ghost" data-go="map">Ver mapa</button><button class="ghost" data-go="ideas">Ideas Iria & Izan</button></div><div class="stats"><div class="stat"><strong>16</strong><span>días</span></div><div class="stat"><strong>8</strong><span>zonas</span></div><div class="stat"><strong>6</strong><span>páginas</span></div><div class="stat"><strong>Waze</strong><span>rutas</span></div></div></div><div class="hero-photo" style="--img:url('${IMG.hero}')"><span class="badge">Indonesia 14-16 días</span><h2>Bali + Gili Meno + Padang Padang</h2><p>Final en villa tropical con piscina privada.</p></div></div>`}
function renderGuide(){const g=guidePages[guidePage];qs('#guide').innerHTML=`<div class="panel pad"><div class="guide-spread"><div class="cover" style="--img:url('${g.img}')"><span class="badge">${String(guidePage+1).padStart(2,'0')}</span><h2>${g.title}</h2><p>${g.sub}</p></div><div class="guide-content"><div><span class="kicker">Travel Guide</span><h2>${g.sub}</h2><p class="lead">${g.text}</p><div>${g.chips.map(c=>`<span class="chip yellow">${c}</span>`).join('')}</div></div><div class="photo-grid">${g.photos.map(p=>`<div class="photo-tile" style="--img:url('${p[1]}')"><span>${p[0]}</span></div>`).join('')}</div><div class="mini-grid"><div class="mini"><b>Reserva primero</b>Vuelos, Gili Meno, villa final y ferry.</div><div class="mini"><b>Evita</b>Días cargados después del ferry y traslados largos antes del vuelo.</div></div><div class="guide-nav"><button id="guidePrev">Página anterior</button><button id="guideNext">Página siguiente</button></div></div></div></div>`;qs('#guidePrev').onclick=()=>{guidePage=(guidePage-1+guidePages.length)%guidePages.length;renderGuide()};qs('#guideNext').onclick=()=>{guidePage=(guidePage+1)%guidePages.length;renderGuide()}}
function renderMap(){const p=places[mapIndex];qs('#map').innerHTML=`<div class="grid"><div class="panel pad"><div class="map-tabs"><button class="${mapMode==='guide'?'active':''}" id="mapGuide">Mapa guía</button><button class="${mapMode==='gps'?'active':''}" id="mapGps">GPS real</button></div><div id="mapArea" class="${mapMode==='guide'?'isomap':'gps-map'}"></div></div><aside class="panel pad map-side"><span class="kicker">${p.days}</span><h2>${p.short}</h2><div class="map-img" style="--img:url('${p.img}')"></div><p>${p.text}</p><span class="chip yellow">${p.cost}</span><div class="links"><a class="waze" href="${waze(p.lat,p.lng)}" target="_blank">Abrir en Waze</a><a href="${gmaps(p.name)}" target="_blank">Google Maps</a></div><div class="mini"><b>Offline</b>${p.offline}<br><br>Para mapa país offline, llevar Bali/Indonesia descargado en una app offline y usar Waze para rutas precargadas.</div><div class="map-list">${places.map((x,i)=>`<button class="map-item ${i===mapIndex?'active':''}" data-map="${i}"><strong>${x.short}</strong><br><span class="muted">${x.days}</span></button>`).join('')}</div></aside></div>`;qs('#mapGuide').onclick=()=>{mapMode='guide';renderMap()};qs('#mapGps').onclick=()=>{mapMode='gps';renderMap()};qsa('[data-map]').forEach(b=>b.onclick=()=>{mapIndex=+b.dataset.map;renderMap()});setTimeout(()=> mapMode==='guide'?drawIsoMap():drawGpsMap(),80)}
function drawIsoMap(){const el=qs('#mapArea');el.innerHTML='<canvas></canvas>'+places.map((p,i)=>`<button class="map-label ${i===mapIndex?'active':''}" data-map="${i}" style="left:${[18,28,42,55,70,78,72,48][i]}%;top:${[70,48,42,55,36,60,67,23][i]}%">${p.short}</button>`).join('');qsa('.map-label').forEach(b=>b.onclick=()=>{mapIndex=+b.dataset.map;renderMap()});const c=qs('canvas',el),ctx=c.getContext('2d');const r=el.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const w=r.width,h=r.height;ctx.fillStyle='#073344';ctx.fillRect(0,0,w,h);for(let i=0;i<80;i++){ctx.strokeStyle=`rgba(255,255,255,${.025+Math.random()*.055})`;ctx.beginPath();ctx.moveTo(Math.random()*w,0);ctx.lineTo(Math.random()*w,h);ctx.stroke()}function island(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0]*w,p[1]*h):ctx.moveTo(p[0]*w,p[1]*h));ctx.closePath();ctx.fillStyle=color;ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=22;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,236,150,.7)';ctx.lineWidth=2;ctx.stroke();}island([[.1,.72],[.2,.64],[.32,.68],[.44,.58],[.55,.63],[.68,.51],[.87,.58],[.77,.72],[.57,.73],[.43,.82],[.27,.76]],'#168953');island([[.45,.37],[.56,.27],[.66,.32],[.63,.44],[.52,.48]],'#2faa63');island([[.73,.21],[.9,.16],[.96,.28],[.81,.34]],'#2a935b');ctx.strokeStyle='#ffd400';ctx.lineWidth=4;ctx.setLineDash([12,10]);ctx.beginPath();[[.18,.70],[.28,.48],[.42,.42],[.55,.55],[.70,.36],[.78,.60],[.72,.67],[.48,.23]].forEach((p,i)=>i?ctx.lineTo(p[0]*w,p[1]*h):ctx.moveTo(p[0]*w,p[1]*h));ctx.stroke();ctx.setLineDash([])}
function drawGpsMap(){const el=qs('#mapArea');if(!window.L){el.innerHTML='<div class="panel pad"><h3>Mapa GPS</h3><p>Con internet se carga OpenStreetMap. Los botones Waze y Google Maps ya funcionan.</p></div>';return}el.innerHTML='';const m=L.map(el).setView([-8.55,115.45],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(m);const pts=places.map(p=>[p.lat,p.lng]);L.polyline(pts,{color:'#ffd400',weight:5,dashArray:'10,10'}).addTo(m);places.forEach((p,i)=>L.marker([p.lat,p.lng]).addTo(m).bindPopup(`<b>${p.short}</b><br>${p.days}`).on('click',()=>{mapIndex=i;renderMap()}));m.fitBounds(L.latLngBounds(pts).pad(.2))}
function renderDays(){const d=days[dayIndex];const applied=getIdeas().filter(x=>x.selected).slice(0,4);qs('#days').innerHTML=`<div class="panel pad"><div class="day-layout"><aside class="day-list">${days.map((x,i)=>`<button class="day-btn ${i===dayIndex?'active':''}" data-day="${i}">Día ${x.d}<br><span class="muted">${x.z}</span></button>`).join('')}</aside><section class="day-main"><div class="day-hero" style="--img:url('${d.img}')"><span class="kicker">Día ${d.d} · ${d.z}</span><h2>${d.t}</h2><p>${d.h}</p></div><div class="day-info"><div class="schedule"><div class="box"><b>Mañana</b>${d.m}</div><div class="box"><b>Comida</b>${d.c}</div><div class="box"><b>Tarde</b>${d.a}</div><div class="box"><b>Noche</b>${d.n}</div></div><div class="details-grid"><div class="box"><b>Hotel</b>${d.hotel}</div><div class="box"><b>Comidas</b>${d.food}</div><div class="box"><b>Transporte</b>${d.transport}</div></div><div class="box" style="margin-top:12px"><b>Enlaces</b><div class="links">${d.links.map(l=>`<a href="${gmaps(l)}" target="_blank">${l}</a>`).join('')}<a class="waze" href="${waze(places[Math.min(mapIndex,places.length-1)].lat,places[Math.min(mapIndex,places.length-1)].lng)}" target="_blank">Waze</a></div></div>${applied.length?`<div class="box" style="margin-top:12px"><b>Ideas seleccionadas de Iria e Izan</b>${applied.map(x=>`<span class="chip orange">${x.title}</span>`).join('')}</div>`:''}</div></section></div></div>`;qsa('[data-day]').forEach(b=>b.onclick=()=>{dayIndex=+b.dataset.day;renderDays()})}
function renderBookings(){const tabs=Object.keys(bookings);qs('#bookings').innerHTML=`<div class="panel pad"><span class="kicker">Reservas</span><h2>Reserva con orden</h2><div class="cta">${tabs.map(t=>`<button class="${t===activeBook?'primary':'ghost'}" data-book="${t}">${t}</button>`).join('')}</div><div class="booking-grid panel scroll" style="background:transparent;border:0;box-shadow:none;padding-top:16px">${bookings[activeBook].map(card).join('')}</div></div>`;qsa('[data-book]').forEach(b=>b.onclick=()=>{activeBook=b.dataset.book;renderBookings()})}let activeBook='vuelos';
function getIdeas(){try{return JSON.parse(localStorage.getItem('nusaIdeasV5')||'[]')}catch{return[]}}function saveIdeas(arr){localStorage.setItem('nusaIdeasV5',JSON.stringify(arr))}
function renderIdeas(){const ideas=getIdeas();qs('#ideas').innerHTML=`<div class="grid"><div class="panel pad"><span class="kicker">Iria & Izan</span><h2>Subid ideas para rehacer el viaje</h2><form class="idea-form" id="ideaForm"><input name="title" placeholder="Nombre de la idea" required><select name="who"><option>Iria</option><option>Izan</option><option>Iria e Izan</option></select><select name="type"><option>Actividad</option><option>Hotel</option><option>Restaurante</option><option>Playa</option><option>Instagram/TikTok</option><option>Documento</option></select><input name="url" placeholder="Enlace IG, hotel, mapa, vídeo..."><textarea class="full" name="notes" rows="4" placeholder="Por qué mola, zona, precio visto, fechas, comentarios..."></textarea><input class="full" type="file" name="file" accept="image/*,.pdf,.doc,.docx"><button class="primary full">Subir idea</button></form></div><div class="panel pad scroll"><h3>Ideas guardadas</h3><div class="idea-grid">${ideas.map((i,idx)=>`<article class="card idea-card ${i.selected?'selected':''}"><div class="card-body"><div class="thumb" style="${i.img?`background-image:url('${i.img}')`:''}"></div><h3>${i.title}</h3><div><span class="chip yellow">${i.who}</span><span class="chip blue">${i.type}</span></div><p>${i.notes||'Sin notas.'}</p><div class="links">${i.url?`<a href="${i.url}" target="_blank">Abrir enlace</a>`:''}<button data-toggle-idea="${idx}">${i.selected?'Quitar':'Aplicar al viaje'}</button><button data-delete-idea="${idx}">Borrar</button></div></div></article>`).join('')||'<p class="lead">Todavía no hay ideas subidas.</p>'}</div></div></div>`;qs('#ideaForm').onsubmit=addIdea;qsa('[data-toggle-idea]').forEach(b=>b.onclick=()=>{const arr=getIdeas();arr[+b.dataset.toggleIdea].selected=!arr[+b.dataset.toggleIdea].selected;saveIdeas(arr);renderIdeas();renderDays();renderFinal()});qsa('[data-delete-idea]').forEach(b=>b.onclick=()=>{const arr=getIdeas();arr.splice(+b.dataset.deleteIdea,1);saveIdeas(arr);renderIdeas();renderDays();renderFinal()})}
function addIdea(e){e.preventDefault();const fd=new FormData(e.target),file=fd.get('file');const base={title:fd.get('title'),who:fd.get('who'),type:fd.get('type'),url:fd.get('url'),notes:fd.get('notes'),selected:false,img:''};if(file&&file.type&&file.type.startsWith('image/')){const r=new FileReader();r.onload=()=>{base.img=r.result;const arr=getIdeas();arr.unshift(base);saveIdeas(arr);renderIdeas()};r.readAsDataURL(file)}else{const arr=getIdeas();arr.unshift(base);saveIdeas(arr);renderIdeas()}}
function renderFinal(){const ideas=getIdeas().filter(x=>x.selected);qs('#final').innerHTML=`<div class="final-grid"><div class="reco"><span class="kicker" style="color:#06120c">Decisión</span><h2>Opción recomendada: equilibrada visual</h2><p>16 días con Ubud, Sidemen, Gili Meno, Uluwatu, Padang Padang y dos noches finales en villa tropical. Reservar primero vuelos, Gili y villa final.</p><div class="cta"><button class="ghost" onclick="window.print()">Guardar PDF</button><button class="ghost" id="downloadSummary">Descargar resumen</button></div></div><div class="panel pad scroll"><h3>Resumen final</h3><div class="summary"><div class="box"><b>Presupuesto</b>2.650-3.450 €/persona orientativo</div><div class="box"><b>Ruta</b>Denpasar · Ubud · Sidemen · Gili Meno · Uluwatu · Villa final</div><div class="box"><b>Prioridad</b>Vuelos + Gili Meno + villa final</div><div class="box"><b>Waze</b>Guardar cada ruta con datos antes de salir</div><div class="box"><b>Ideas aplicadas</b>${ideas.length?ideas.map(i=>`<span class="chip orange">${i.title}</span>`).join(''):'Ninguna todavía'}</div><div class="box"><b>Siguiente acción</b>Abrir reservas, comparar 3 ventanas y bloquear alojamientos críticos.</div></div></div></div>`;qs('#downloadSummary').onclick=downloadSummary}
function downloadSummary(){const txt='Nusa Travel OS · Indonesia\nRuta: Denpasar · Ubud · Sidemen · Gili Meno · Uluwatu · Villa final\nSiguiente acción: vuelos, Gili Meno y villa final.\nIdeas aplicadas: '+getIdeas().filter(i=>i.selected).map(i=>i.title).join(', ');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));a.download='resumen-indonesia.txt';a.click()}
function bind(){qsa('[data-go]').forEach(b=>b.onclick=()=>go(screens.indexOf(b.dataset.go)));qs('#prevScreen').onclick=()=>go(current-1);qs('#nextScreen').onclick=()=>go(current+1);qs('#soundToggle').onclick=toggleSound;window.onresize=()=>{if(screens[current]==='map'&&mapMode==='guide')drawIsoMap()}}
function go(i){current=Math.max(0,Math.min(screens.length-1,i));qsa('.screen').forEach(s=>s.classList.remove('active'));qs('#'+screens[current]).classList.add('active');qsa('.top-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===screens[current]));renderDots();if(screens[current]==='map')setTimeout(()=>mapMode==='guide'?drawIsoMap():drawGpsMap(),80)}
function renderDots(){qs('#dots').innerHTML=screens.map((s,i)=>`<button class="dot ${i===current?'active':''}" data-dot="${i}"></button>`).join('');qsa('[data-dot]').forEach(d=>d.onclick=()=>go(+d.dataset.dot))}
function renderAll(){renderHome();renderGuide();renderMap();renderDays();renderBookings();renderIdeas();renderFinal();renderDots();bind();go(0)}
function toggleSound(){soundOn?stopSound():startSound()}function startSound(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),master=ctx.createGain();master.gain.value=.20;master.connect(ctx.destination);const buf=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.22;const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;src.loop=true;f.type='lowpass';f.frequency.value=900;g.gain.value=.5;src.connect(f).connect(g).connect(master);src.start();const chirps=setInterval(()=>{const o=ctx.createOscillator(),gg=ctx.createGain();o.frequency.value=900+Math.random()*1800;gg.gain.setValueAtTime(.0001,ctx.currentTime);gg.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+.05);gg.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.45);o.connect(gg).connect(master);o.start();o.stop(ctx.currentTime+.5)},1300);audio={ctx,src,chirps};soundOn=true;qs('#soundToggle').textContent='Selva OFF';qs('#soundToggle').classList.add('playing')}function stopSound(){if(!audio)return;clearInterval(audio.chirps);try{audio.src.stop();audio.ctx.close()}catch{}audio=null;soundOn=false;qs('#soundToggle').textContent='Selva ON';qs('#soundToggle').classList.remove('playing')}
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
document.addEventListener('DOMContentLoaded',renderAll);
