/* eslint-disable @typescript-eslint/no-explicit-any */
import { PrismaClient } from '@prisma/client'
import { readFileSync } from 'fs'

const db = new PrismaClient()

const IMG = {
  hero: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1800&q=88',
  temple: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=88',
  rice: 'https://images.unsplash.com/photo-1559628233-100c798642d4?auto=format&fit=crop&w=1600&q=88',
  beach: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=88',
  villa: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=88',
  snorkel: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=88',
  waterfall: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=88',
  sunset: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88',
  jungle: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&q=88',
  plane: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=88',
  food: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1600&q=88',
  market: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=1600&q=88',
}

// 16-day Indonesia itinerary — Bali · Gili Meno · Padang Padang · villa final
const itinerary = [
  {
    day: '1', zone: 'Llegada · Denpasar', title: 'Aterrizaje en Bali y primer respiro tropical',
    image: IMG.plane, coordsLat: -8.7467, coordsLng: 115.1668,
    morning: 'Vuelo internacional y llegada al aeropuerto Ngurah Rai de Denpasar. Trámites de visado a la llegada y control migratorio.',
    lunch: 'Comida ligera según la hora de aterrizaje. Opción cómoda en el aeropuerto o parada en ruta hacia Ubud.',
    afternoon: 'Traslado privado con aire acondicionado hacia Ubud. El recorrido atraviesa el sur de Bali y sube hacia la selva central.',
    night: 'Cena tranquila en el hotel y descanso. La jornada se vive sin agenda cargada para empezar a ritmo balinés.',
    transport: 'Aeropuerto Ngurah Rai → Ubud · 1 h 15 min – 2 h según tráfico',
    cost: 'Traslado 18 – 35 € por coche · Visado VoA ~30 €/persona',
    time: 'Llegada, instalarse, descansar',
    mapQuery: 'Ngurah Rai International Airport to Ubud',
    wazeQuery: 'Ubud Bali',
    advice: 'El primer día se disfruta aterrizando sin prisas; el jet-lag se gestiona mejor con luz natural y una buena comida.',
    hotelName: 'Ubud Village Hotel & Spa', hotelPrice: '90 – 140 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/ubud-village.en.html',
    mealLunchName: 'Warung Local Ubud', mealLunchPrice: '6 – 12 €/persona',
    mealDinnerName: 'Locavore (alta cocina balinesa)', mealDinnerPrice: '70 – 120 €/persona',
    mealDinnerLink: 'https://www.locavore.com/',
  },
  {
    day: '2', zone: 'Ubud', title: 'Arrozales de Tegallalang y piscina entre la selva',
    image: IMG.rice, coordsLat: -8.4287, coordsLng: 115.2794,
    morning: 'Paseo matutino por los arrozales en terraza de Tegallalang con la luz dorada del amanecer y el sonido del agua.',
    lunch: 'Comida con vistas a los arrozales en un warung tradicional al borde de la terraza.',
    afternoon: 'Regreso al hotel para piscina, masaje balinés y paseo tranquilo por el centro de Ubud.',
    night: 'Cena en un restaurante con jardín y velas, ambiente sereno en plena selva.',
    transport: 'Coche local o taxi corto · 20 – 40 min',
    cost: 'Entrada arrozales ~1 €/persona · Actividades 25 – 55 €',
    time: '08:00 – 21:30',
    mapQuery: 'Tegallalang Rice Terrace',
    wazeQuery: 'Tegallalang Rice Terrace Bali',
    advice: 'Los arrozales amanecen espectaculares y casi vacíos; la luz del mediodía endurece las fotos y la temperatura sube.',
    hotelName: 'Ubud Village Hotel & Spa', hotelPrice: '90 – 140 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/ubud-village.en.html',
    mealLunchName: 'Tegallalang Rice Terrace Warung', mealLunchPrice: '5 – 10 €/persona',
    mealDinnerName: 'Bridges Bali', mealDinnerPrice: '35 – 60 €/persona',
    mealDinnerLink: 'https://www.bridgesbali.com/',
  },
  {
    day: '3', zone: 'Ubud', title: 'Templos, agua sagrada y mercado artesanal',
    image: IMG.temple, coordsLat: -8.4244, coordsLng: 115.3177,
    morning: 'Visita al templo del agua Tirta Empul, donde se realiza el rito de purificación melukat, y a la cueva Goa Gajah.',
    lunch: 'Comida balinesa en Ubud con pausa para el calor del mediodía.',
    afternoon: 'Mercado de Ubud, talleres de plata y clase express de cocina balinesa.',
    night: 'Cena familiar animada y paseo corto por las calles iluminadas.',
    transport: 'Coche privado medio día · 4 – 5 h',
    cost: 'Guía + entradas 45 – 90 €/grupo · Clase cocina 25 – 40 €/persona',
    time: '08:00 – 22:00',
    mapQuery: 'Tirta Empul Temple',
    wazeQuery: 'Tirta Empul Bali',
    advice: 'Se entrega un sarong en el templo; conviene vestir respetuosamente y llevar calzado fácil de quitar.',
    hotelName: 'Ubud Village Hotel & Spa', hotelPrice: '90 – 140 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/ubud-village.en.html',
    mealLunchName: 'Bebek Bengil (Dirty Duck Diner)', mealLunchPrice: '12 – 20 €/persona',
    mealLunchLink: 'https://www.bebekbengil.com/',
    mealDinnerName: 'Milk & Madu Ubud', mealDinnerPrice: '12 – 22 €/persona',
    mealDinnerLink: 'https://milkandmadu.com/',
  },
  {
    day: '4', zone: 'Ubud', title: 'Cascadas de la jungla y aventura suave',
    image: IMG.waterfall, coordsLat: -8.4744, coordsLng: 115.3326,
    morning: 'Caminata temprana a la cascada Tibumana y a la cascada Kanto Lampo entre vegetación densa.',
    lunch: 'Comida junto al agua, en un café rústico con cañas de bambú y puentes de madera.',
    afternoon: 'Cafetería con vistas, columpio de selva opcional o ruta suave en quad si encaja con el grupo.',
    night: 'Noche libre en Ubud con ambiente relajado.',
    transport: 'Coche privado 6 – 8 h · conductor espera',
    cost: 'Entradas + actividades 65 – 120 €/grupo',
    time: '07:30 – 21:30',
    mapQuery: 'Tibumana Waterfall Bali',
    wazeQuery: 'Tibumana Waterfall',
    advice: 'Calzado con agarre para las rocas húmedas; en agosto conviene llegar temprano para evitar grupos.',
    hotelName: 'Ubud Village Hotel & Spa', hotelPrice: '90 – 140 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/ubud-village.en.html',
    mealLunchName: 'Kanto Lampo Warung', mealLunchPrice: '5 – 10 €/persona',
    mealDinnerName: 'Watercress Cafe Ubud', mealDinnerPrice: '10 – 18 €/persona',
    mealDinnerLink: 'https://www.watercressubud.com/',
  },
  {
    day: '5', zone: 'Ubud', title: 'Día flexible: familia, fotos y descanso',
    image: IMG.jungle, coordsLat: -8.5069, coordsLng: 115.2625,
    morning: 'Yoga suave, spa o paseo por el Monkey Forest de Ubud entre banianos centenarios.',
    lunch: 'Comida bonita en un café de especialidad de Ubud.',
    afternoon: 'Tiempo de compras, piscina y descanso real sin agenda.',
    night: 'Cena especial para el grupo con ambiente de viaje.',
    transport: 'A pie + taxis cortos',
    cost: 'Spa 40 – 110 €/persona · Monkey Forest ~4 €/persona',
    time: '09:30 – 22:30',
    mapQuery: 'Ubud Monkey Forest',
    wazeQuery: 'Ubud Monkey Forest',
    advice: 'Un día flexible da aire al viaje y permite repetir lo que más haya gustado sin sensación de carrera.',
    hotelName: 'Ubud Village Hotel & Spa', hotelPrice: '90 – 140 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/ubud-village.en.html',
    mealLunchName: 'Anomali Coffee Ubud', mealLunchPrice: '6 – 14 €/persona',
    mealDinnerName: 'Aka Restaurant', mealDinnerPrice: '20 – 35 €/persona',
  },
  {
    day: '6', zone: 'Sidemen', title: 'Valle de Sidemen y arrozales auténticos',
    image: IMG.rice, coordsLat: -8.4667, coordsLng: 115.4333,
    morning: 'Salida hacia Sidemen con paradas fotográficas en terrazas y pueblos de tejedores.',
    lunch: 'Comida con vistas al valle y al volcán Agung al fondo.',
    afternoon: 'Paseo rural entre arrozales, mirador y piscina con vista panorámica.',
    night: 'Alojamiento en Sidemen con vistas o regreso a Ubud según la ruta elegida.',
    transport: 'Ubud → Sidemen · 1 h 30 min – 2 h en coche escénico',
    cost: 'Coche + actividad 55 – 120 €/grupo',
    time: '08:00 – 21:00',
    mapQuery: 'Sidemen Bali',
    wazeQuery: 'Sidemen Bali',
    advice: 'Sidemen es la transición perfecta entre la selva de Ubud y el salto a las islas Gili.',
    hotelName: 'Wapa di Ume Sidemen', hotelPrice: '75 – 130 €/noche',
    hotelLink: 'https://www.wapadiume.com/sidemen',
    mealLunchName: 'Sameki Restaurant Sidemen', mealLunchPrice: '8 – 15 €/persona',
    mealDinnerName: 'Cena en el hotel del valle', mealDinnerPrice: '15 – 25 €/persona',
  },
  {
    day: '7', zone: 'Gili Meno', title: 'Barco rápido a Gili Meno y modo isla',
    image: IMG.snorkel, coordsLat: -8.3517, coordsLng: 116.0584,
    morning: 'Traslado temprano al puerto de Padang Bai y barco rápido a Gili Meno.',
    lunch: 'Llegada a la isla, check-in y comida frente al mar.',
    afternoon: 'Reconocimiento de la isla a pie o en bici, hamaca y primer baño turquesa.',
    night: 'Cena con los pies en la arena y estrellas sobre el estrecho de Lombok.',
    transport: 'Coche + ferry rápido · cruce 1 h 30 – 2 h',
    cost: 'Ferry 35 – 65 €/persona + traslado 20 – 35 €',
    time: '06:30 – 21:00',
    mapQuery: 'Padang Bai to Gili Meno',
    wazeQuery: 'Gili Meno',
    advice: 'Los barcos de mañana navegan con mejor mar; conviene elegir operador con buenas reseñas.',
    hotelName: 'Seri Resort Gili Meno', hotelPrice: '85 – 160 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/seri-resort-gili-meno.en.html',
    mealLunchName: 'Seri Resort Beachfront', mealLunchPrice: '10 – 18 €/persona',
    mealDinnerName: 'Sasak Village Gili Meno', mealDinnerPrice: '12 – 22 €/persona',
  },
  {
    day: '8', zone: 'Gili Meno', title: 'Snorkel con tortugas y estatuas submarinas',
    image: IMG.snorkel, coordsLat: -8.3558, coordsLng: 116.0529,
    morning: 'Salida en barca local para snorkel en Turtle Point y en las estatuas underwater de Gili Meno.',
    lunch: 'Comida sencilla de playa en un warung junto al mar.',
    afternoon: 'Bicicleta alrededor de la isla, hamacas y baño libre.',
    night: 'Atardecer tranquilo mirando a Lombok.',
    transport: 'Barca local + bici',
    cost: 'Snorkel 18 – 45 €/persona · Bici ~3 €/día',
    time: '08:30 – 21:30',
    mapQuery: 'Gili Meno Turtle Point',
    wazeQuery: 'Gili Meno Turtle Point',
    advice: 'Camiseta UV y crema reef-safe; las fotos subacuáticas aquí merecen la pena.',
    hotelName: 'Seri Resort Gili Meno', hotelPrice: '85 – 160 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/seri-resort-gili-meno.en.html',
    mealLunchName: 'Ya Ya Warung Gili Meno', mealLunchPrice: '6 – 12 €/persona',
    mealDinnerName: 'Mahamaya Beach Restaurant', mealDinnerPrice: '18 – 30 €/persona',
  },
  {
    day: '9', zone: 'Gili Meno', title: 'Isla sin prisa y plan en familia',
    image: IMG.beach, coordsLat: -8.3517, coordsLng: 116.0584,
    morning: 'Vuelta a la isla caminando o en bici por la costa oeste.',
    lunch: 'Comida junto al mar con pescado del día.',
    afternoon: 'Kayak, paddle o playa tranquila según el ánimo del grupo.',
    night: 'Cena especial mirando a la línea de costa de Lombok.',
    transport: 'Bici / caminar / cidomo (carro de caballos)',
    cost: 'Actividades 15 – 70 €/persona',
    time: '09:00 – 22:00',
    mapQuery: 'Gili Meno Island',
    wazeQuery: 'Gili Meno Island',
    advice: 'Gili Meno se disfruta con agenda ligera; esa es su forma de lujo.',
    hotelName: 'Seri Resort Gili Meno', hotelPrice: '85 – 160 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/seri-resort-gili-meno.en.html',
    mealLunchName: 'Din Meno Beach Cafe', mealLunchPrice: '8 – 14 €/persona',
    mealDinnerName: 'Kafka Restaurant Gili Meno', mealDinnerPrice: '15 – 25 €/persona',
  },
  {
    day: '10', zone: 'Gili Meno', title: 'Día colchón de mar, fotos y descanso',
    image: IMG.snorkel, coordsLat: -8.3480, coordsLng: 116.0620,
    morning: 'Segundo snorkel o mañana en la playa norte, más tranquila.',
    lunch: 'Comida sin desplazamientos, frente al agua.',
    afternoon: 'Tiempo libre para cada uno: lectura, baño, fotos, pareja o hijos.',
    night: 'Última noche de isla con despedida del mar.',
    transport: 'Sin coche',
    cost: '20 – 80 €/persona',
    time: 'Libre',
    mapQuery: 'Gili Meno North Beach',
    wazeQuery: 'Gili Meno',
    advice: 'Este día cubre mala mar, cansancio o ganas de repetir lo mejor de la isla.',
    hotelName: 'Seri Resort Gili Meno', hotelPrice: '85 – 160 €/noche',
    hotelLink: 'https://www.booking.com/hotel/id/seri-resort-gili-meno.en.html',
    mealLunchName: 'Beach BBQ en el hotel', mealLunchPrice: '12 – 20 €/persona',
    mealDinnerName: 'Sunset Seafood BBQ', mealDinnerPrice: '18 – 32 €/persona',
  },
  {
    day: '11', zone: 'Uluwatu', title: 'Regreso a Bali y acantilados del sur',
    image: IMG.sunset, coordsLat: -8.8291, coordsLng: 115.0849,
    morning: 'Barco de vuelta a Bali desde Gili Meno a Padang Bai o Sanur.',
    lunch: 'Comida cerca del puerto o ya en Uluwatu.',
    afternoon: 'Check-in en la zona sur y primer mirador sobre los acantilados de caliza.',
    night: 'Cena con vistas al océano Índico.',
    transport: 'Ferry + coche privado · 2 – 4 h total',
    cost: 'Ferry + traslado 70 – 150 €/grupo',
    time: '07:30 – 22:00',
    mapQuery: 'Gili Meno to Uluwatu Bali',
    wazeQuery: 'Uluwatu Bali',
    advice: 'Tras el ferry conviene un plan suave de atardecer y cena; el tráfico del sur pesa.',
    hotelName: 'Uluwatu Surf Villas / Le Bamboo', hotelPrice: '110 – 220 €/noche',
    hotelLink: 'https://www.booking.com/region/id/uluwatu.en.html',
    mealLunchName: 'Cafe del Mar Bali', mealLunchPrice: '15 – 25 €/persona',
    mealDinnerName: 'Single Fin Bali (cliff bar)', mealDinnerPrice: '15 – 30 €/persona',
    mealDinnerLink: 'https://www.singlefinbali.com/',
  },
  {
    day: '12', zone: 'Padang Padang', title: 'Playa icónica, surf suave y beach club',
    image: IMG.beach, coordsLat: -8.8107, coordsLng: 115.1024,
    morning: 'Padang Padang temprano, fotos antes de la masa y baño en agua cristalina.',
    lunch: 'Comida en Bingin Beach o en la zona de Uluwatu.',
    afternoon: 'Clase de surf suave o tarde en un beach club con piscina infinita.',
    night: 'Atardecer en acantilado y cena en un sitio con ambiente.',
    transport: 'Taxis cortos o conductor local',
    cost: 'Playa 1 – 3 €/persona · Surf 25 – 50 €/persona · Beach club 30 – 120 €/persona',
    time: '08:00 – 23:00',
    mapQuery: 'Padang Padang Beach Bali',
    wazeQuery: 'Padang Padang Beach Bali',
    advice: 'La playa es pequeña: se disfruta temprano o al final de la tarde; para estar horas, combinar con Bingin o Thomas Beach.',
    hotelName: 'Uluwatu Surf Villas / Le Bamboo', hotelPrice: '110 – 220 €/noche',
    hotelLink: 'https://www.booking.com/region/id/uluwatu.en.html',
    mealLunchName: 'Kellys Warung Bingin', mealLunchPrice: '6 – 12 €/persona',
    mealDinnerName: 'Savaya Bali (beach club)', mealDinnerPrice: '30 – 60 €/persona',
    mealDinnerLink: 'https://www.savayabali.com/',
  },
  {
    day: '13', zone: 'Uluwatu', title: 'Templo de Uluwatu y danza Kecak al atardecer',
    image: IMG.temple, coordsLat: -8.8291, coordsLng: 115.0849,
    morning: 'Mañana libre: piscina, café o playa escondida del sur.',
    lunch: 'Comida sin correr en un cafe con vistas al mar.',
    afternoon: 'Templo de Uluwatu sobre el acantilado y danza Kecak con el atardecer de fondo.',
    night: 'Cena especial en Uluwatu con despedida del sur.',
    transport: 'Coche local / taxi',
    cost: 'Entrada templo ~1 €/persona · Kecak 13 – 18 €/persona',
    time: '16:00 – 22:30',
    mapQuery: 'Uluwatu Temple',
    wazeQuery: 'Uluwatu Temple Bali',
    advice: 'En el templo hay monos: conviene llevar gafas y móvil guardados. El Kecak se compra con margen.',
    hotelName: 'Uluwatu Surf Villas / Le Bamboo', hotelPrice: '110 – 220 €/noche',
    hotelLink: 'https://www.booking.com/region/id/uluwatu.en.html',
    mealLunchName: 'Drifter Cafe Uluwatu', mealLunchPrice: '10 – 18 €/persona',
    mealDinnerName: 'JuMaNa Bali at Bvlgari', mealDinnerPrice: '70 – 130 €/persona',
  },
  {
    day: '14', zone: 'Villa final · Munduk', title: 'Llegada a la villa de selva con piscina privada',
    image: IMG.villa, coordsLat: -8.267, coordsLng: 115.066,
    morning: 'Traslado sin madrugar hacia Munduk, en las tierras altas del norte de Bali.',
    lunch: 'Comida en ruta o en la villa con vistas a las plantaciones.',
    afternoon: 'Check-in, piscina privada, sesión de fotos y descanso entre la niebla de montaña.',
    night: 'Cena en la villa con ambiente íntimo de cierre de viaje.',
    transport: 'Uluwatu → Munduk · 2 h 30 – 3 h 30',
    cost: 'Coche 55 – 90 € + villa 180 – 480 €/noche',
    time: '10:00 – 22:00',
    mapQuery: 'Munduk Bali private pool villa',
    wazeQuery: 'Munduk Bali',
    advice: 'Este día es para que el alojamiento sea protagonista: sin excursiones, solo piscina y vistas.',
    hotelName: 'Munduk Moding Plantation Villa', hotelPrice: '180 – 320 €/noche',
    hotelLink: 'https://www.mundukmodaglobal.com/',
    mealLunchName: 'Alila Munduk Restaurant', mealLunchPrice: '15 – 28 €/persona',
    mealDinnerName: 'Cena en la villa privada', mealDinnerPrice: '40 – 80 €/persona',
  },
  {
    day: '15', zone: 'Villa final · Munduk', title: 'Masaje, cascada y cierre del viaje',
    image: IMG.jungle, coordsLat: -8.2550, coordsLng: 115.0850,
    morning: 'Desayuno lento en la terraza y masaje con vistas a la selva.',
    lunch: 'Comida en la villa o en un restaurante panorámico cercano.',
    afternoon: 'Cascada cercana de Munduk o sesión de fotos en plantación de café.',
    night: 'Cena final de viaje con brindis y resumen del recorrido.',
    transport: 'Coche corto opcional',
    cost: 'Spa 50 – 140 €/persona · Cascada ~2 €/persona',
    time: '09:30 – 22:30',
    mapQuery: 'Munduk Waterfalls Bali',
    wazeQuery: 'Munduk Waterfall Bali',
    advice: 'Último día completo: una sola actividad y mucho margen para saborear el cierre.',
    hotelName: 'Munduk Moding Plantation Villa', hotelPrice: '180 – 320 €/noche',
    hotelLink: 'https://www.mundukmodaglobal.com/',
    mealLunchName: 'Munduk Moding Plantation', mealLunchPrice: '15 – 28 €/persona',
    mealDinnerName: 'Despedida cena en la villa', mealDinnerPrice: '50 – 90 €/persona',
  },
  {
    day: '16', zone: 'Salida · Denpasar', title: 'Regreso al aeropuerto con margen',
    image: IMG.plane, coordsLat: -8.7467, coordsLng: 115.1668,
    morning: 'Desayuno final y salida sin prisas desde la villa.',
    lunch: 'Comida en ruta hacia el aeropuerto, parada en un pueblo o en Denpasar.',
    afternoon: 'Traslado a Denpasar con margen amplio para el vuelo internacional.',
    night: 'Vuelo de regreso con todo el viaje cerrado.',
    transport: 'Munduk → Aeropuerto Ngurah Rai · 2 h 30 – 4 h',
    cost: 'Coche 45 – 85 €',
    time: 'Según vuelo',
    mapQuery: 'Munduk to Ngurah Rai International Airport',
    wazeQuery: 'Ngurah Rai International Airport',
    advice: 'En Bali el tráfico puede romper el día; salir con margen es parte del plan de regreso.',
    hotelName: '— (vuelo nocturno)', hotelPrice: '—',
    mealLunchName: 'Comida en ruta / Denpasar', mealLunchPrice: '8 – 16 €/persona',
    mealDinnerName: 'Aeropuerto / vuelo', mealDinnerPrice: 'según aerolínea',
  },
]

// Guide entries — transport, restaurants, beaches, activities, tips (max detail)
const guide: Array<{ category: string; zone: string; title: string; text: string; price?: string; time?: string; link?: string; wazeQuery?: string; image?: string; order: number }> = [
  // TRANSPORTES
  { category: 'transport', zone: 'Internacional', title: 'Vuelo Madrid/Barcelona → Denpasar', text: 'Vuelo con una escala razonable en Qatar, Emirates, Turkish, Etihad o Singapore Airlines. Comparar tres ventanas de agosto: 10-26, 14-29 y 18-1.', price: '850 – 1.550 €/persona', time: '18 – 22 h total', link: 'https://www.skyscanner.es/transporte/vuelos/mad/dps/', wazeQuery: '', image: IMG.plane, order: 1 },
  { category: 'transport', zone: 'Denpasar → Ubud', title: 'Traslado aeropuerto → Ubud', text: 'Traslado privado con aire acondicionado. Se reserva online o se toma un taxi oficial en el aeropuerto. Grab/Gojek también disponibles.', price: '18 – 35 € por coche', time: '1 h 15 – 2 h', wazeQuery: 'Ubud Bali', image: IMG.plane, order: 2 },
  { category: 'transport', zone: 'Ubud → Sidemen', title: 'Coche escénico Ubud → Sidemen', text: 'Ruta por la falda del volcán Agung con paradas en terrazas y pueblos. Conductor privado recomendado.', price: '45 – 70 €/día coche', time: '1 h 30 – 2 h', wazeQuery: 'Sidemen Bali', image: IMG.rice, order: 3 },
  { category: 'transport', zone: 'Padang Bai → Gili Meno', title: 'Ferry rápido a Gili Meno', text: 'Barco rápido desde Padang Bai o Sanur. Operadores recomendados: Eka Jaya, BlueWater Express, Gili Cat. Horario de mañana para mejor mar.', price: '35 – 65 €/persona/trayecto', time: '1 h 30 – 2 h cruce', link: 'https://www.eka-jaya.com/', wazeQuery: 'Padang Bai Harbour', image: IMG.snorkel, order: 4 },
  { category: 'transport', zone: 'Gili Meno → Uluwatu', title: 'Regreso a Bali y traslado al sur', text: 'Ferry de vuelta + coche privado al sur. Día de transición sin actividades fuertes.', price: '70 – 150 €/grupo + ferry', time: '2 – 4 h total', wazeQuery: 'Uluwatu Bali', image: IMG.sunset, order: 5 },
  { category: 'transport', zone: 'Uluwatu → Munduk', title: 'Traslado a la villa final de montaña', text: 'Subida a las tierras altas del norte con plantaciones de café y niebla de montaña.', price: '55 – 90 € coche', time: '2 h 30 – 3 h 30', wazeQuery: 'Munduk Bali', image: IMG.villa, order: 6 },
  { category: 'transport', zone: 'Munduk → Aeropuerto', title: 'Salida al aeropuerto', text: 'Traslado final con margen amplio. El tráfico de Bali castiga la prisa.', price: '45 – 85 € coche', time: '2 h 30 – 4 h', wazeQuery: 'Ngurah Rai International Airport', image: IMG.plane, order: 7 },
  { category: 'transport', zone: 'Isla', title: 'Movilidad en Gili Meno', text: 'Isla sin coches: bicicleta, caminar o cidomo (carro de caballos). Todo a mano.', price: 'Bici ~3 €/día · cidomo 5 – 12 €', time: '30 min cruzar la isla', wazeQuery: 'Gili Meno', image: IMG.beach, order: 8 },

  // RESTAURANTES
  { category: 'restaurant', zone: 'Ubud', title: 'Locavore', text: 'Alta cocina balinesa con producto local. Estrella Michelin verde. Reserva imprescindible con semanas de antelación.', price: '70 – 120 €/persona', time: 'Cena · 19:00 – 22:30', link: 'https://www.locavore.com/', wazeQuery: 'Locavore Ubud', image: IMG.food, order: 1 },
  { category: 'restaurant', zone: 'Ubud', title: 'Bebek Bengil (Dirty Duck)', text: 'Pato balinés crujiente clásico desde 1990. Vistas a arrozales desde la terraza.', price: '12 – 20 €/persona', time: '12:00 – 22:00', link: 'https://www.bebekbengil.com/', wazeQuery: 'Bebek Bengil Ubud', image: IMG.food, order: 2 },
  { category: 'restaurant', zone: 'Ubud', title: 'Bridges Bali', text: 'Cocina internacional junto al río Campuhan. Ambiente elegante para cena especial.', price: '35 – 60 €/persona', time: 'Cena · 17:00 – 23:00', link: 'https://www.bridgesbali.com/', wazeQuery: 'Bridges Bali Ubud', image: IMG.food, order: 3 },
  { category: 'restaurant', zone: 'Ubud', title: 'Watercress Cafe', text: 'Café de especialidad y bowls. Ideal para desayunos y comidas ligeras.', price: '10 – 18 €/persona', time: '08:00 – 22:00', link: 'https://www.watercressubud.com/', wazeQuery: 'Watercress Ubud', image: IMG.food, order: 4 },
  { category: 'restaurant', zone: 'Sidemen', title: 'Sameki Restaurant', text: 'Cocina casera balinesa con vistas al valle de Sidemen y al Agung.', price: '8 – 15 €/persona', time: '11:00 – 21:00', wazeQuery: 'Sameki Sidemen', image: IMG.food, order: 5 },
  { category: 'restaurant', zone: 'Gili Meno', title: 'Mahamaya Beach Restaurant', text: 'Cena frente al mar con menú de pescado del día y cócteles al atardecer.', price: '18 – 30 €/persona', time: 'Cena · 18:00 – 22:30', wazeQuery: 'Mahamaya Gili Meno', image: IMG.food, order: 6 },
  { category: 'restaurant', zone: 'Gili Meno', title: 'Ya Ya Warung', text: 'Comida local barata y generosa frente a la playa. Mejor relación calidad-precio de la isla.', price: '6 – 12 €/persona', time: '10:00 – 21:00', wazeQuery: 'Ya Ya Warung Gili Meno', image: IMG.food, order: 7 },
  { category: 'restaurant', zone: 'Uluwatu', title: 'Single Fin Bali', text: 'Bar sobre acantilado con el mejor atardecer de surf de Bali. Ambient music los domingos.', price: '15 – 30 €/persona', time: '12:00 – 24:00', link: 'https://www.singlefinbali.com/', wazeQuery: 'Single Fin Bali', image: IMG.food, order: 8 },
  { category: 'restaurant', zone: 'Uluwatu', title: 'Savaya Bali', text: 'Beach club de diseño con piscina infinita sobre el océano y cocina mediterránea-asiática.', price: '30 – 60 €/persona', time: '10:00 – 24:00', link: 'https://www.savayabali.com/', wazeQuery: 'Savaya Bali', image: IMG.food, order: 9 },
  { category: 'restaurant', zone: 'Uluwatu', title: 'JuMaNa at Bvlgari', text: 'Alta cocina mediterránea en el resort Bvlgari con vistas al Índico. Cena de ocasión.', price: '70 – 130 €/persona', time: 'Cena · 18:00 – 23:00', wazeQuery: 'Bvlgari Resort Uluwatu', image: IMG.food, order: 10 },
  { category: 'restaurant', zone: 'Munduk', title: 'Munduk Moding Plantation', text: 'Restaurante en plantación de café con vistas a la selva y cocina farm-to-table.', price: '15 – 28 €/persona', time: '07:00 – 22:00', link: 'https://www.mundukmodaglobal.com/', wazeQuery: 'Munduk Moding Plantation', image: IMG.food, order: 11 },

  // PLAYAS
  { category: 'beach', zone: 'Uluwatu', title: 'Padang Padang Beach', text: 'Playa icónica entre dos acantilados. Acceso por escaleras. Aparece en la película Eat Pray Love. Mejor temprano o al atardecer.', price: '1 – 3 €/persona entrada', time: '08:00 – 18:00', wazeQuery: 'Padang Padang Beach Bali', image: IMG.beach, order: 1 },
  { category: 'beach', zone: 'Uluwatu', title: 'Bingin Beach', text: 'Playa de surf con warungs sobre la arena. Acceso por escaleras empinadas. Ambiente relajado y atardeceres brutales.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Bingin Beach Bali', image: IMG.beach, order: 2 },
  { category: 'beach', zone: 'Uluwatu', title: 'Thomas Beach', text: 'Playa más tranquila del sur, ideal para escapar de la masa de Padang Padang. Acceso por escaleras.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Thomas Beach Uluwatu', image: IMG.beach, order: 3 },
  { category: 'beach', zone: 'Uluwatu', title: 'Nyang Nyang Beach', text: 'Playa larga y virgen al final de una caminata. Una de las más bonitas y menos visitadas de Bali.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Nyang Nyang Beach Bali', image: IMG.beach, order: 4 },
  { category: 'beach', zone: 'Gili Meno', title: 'Playa oeste Gili Meno', text: 'Arena blanca y agua turquesa con atardeceres sobre Lombok. La zona mejor para dormir en la isla.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Gili Meno West Beach', image: IMG.beach, order: 5 },
  { category: 'beach', zone: 'Gili Meno', title: 'Playa norte Gili Meno', text: 'Tramo más tranquilo, ideal para snorkel desde la orilla y para alejarse de los hoteles.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Gili Meno North Beach', image: IMG.beach, order: 6 },
  { category: 'beach', zone: 'Sanur', title: 'Sanur Beach', text: 'Playa tranquila del este con paseo marítimo. Buena base antes de un ferry a las Gili.', price: 'Acceso libre', time: 'Todo el día', wazeQuery: 'Sanur Beach Bali', image: IMG.beach, order: 7 },

  // ACTIVIDADES
  { category: 'activity', zone: 'Gili Meno', title: 'Snorkel con tortugas', text: 'La actividad estrella: tortugas, estatuas submarinas y coral. Salida en barca local.', price: '18 – 45 €/persona', time: '08:30 – 12:00', wazeQuery: 'Gili Meno Turtle Point', image: IMG.snorkel, order: 1 },
  { category: 'activity', zone: 'Uluwatu', title: 'Danza Kecak en Uluwatu', text: 'Espectáculo al atardecer en el templo sobre el acantilado. Coro de 70 hombres y drama Ramayana.', price: '13 – 18 €/persona', time: '18:00 – 19:30', wazeQuery: 'Uluwatu Temple Bali', image: IMG.temple, order: 2 },
  { category: 'activity', zone: 'Ubud', title: 'Arrozales de Tegallalang', text: 'Terrazas de arroz Patrimonio UNESCO. Columpios y puentes de fotos. Mejor al amanecer.', price: '1 – 15 €/persona', time: '07:00 – 10:30', wazeQuery: 'Tegallalang Rice Terrace', image: IMG.rice, order: 3 },
  { category: 'activity', zone: 'Ubud', title: 'Purificación en Tirta Empul', text: 'Rito melukat en el templo del agua sagrada. Sarong entregado en el lugar.', price: '~2 €/persona', time: '08:00 – 12:00', wazeQuery: 'Tirta Empul Temple', image: IMG.temple, order: 4 },
  { category: 'activity', zone: 'Ubud', title: 'Cascadas Tibumana y Kanto Lampo', text: 'Ruta de cascadas en la jungla. Calzado con agarre imprescindible.', price: '2 – 8 €/persona', time: '07:30 – 12:30', wazeQuery: 'Tibumana Waterfall', image: IMG.waterfall, order: 5 },
  { category: 'activity', zone: 'Uluwatu', title: 'Clase de surf suave', text: 'Clase para principiantes en Padang Padang o playa de Bingin. Tabla y licra incluidas.', price: '25 – 50 €/persona', time: '09:00 – 11:00', wazeQuery: 'Padang Padang Surf School', image: IMG.beach, order: 6 },
  { category: 'activity', zone: 'Uluwatu', title: 'Beach club con atardecer', text: 'Tarde de piscina, música y cóctoles en Savaya o Finns. Reserva de mesa en agosto.', price: '30 – 120 €/persona', time: '15:30 – 20:30', wazeQuery: 'Savaya Bali', image: IMG.sunset, order: 7 },
  { category: 'activity', zone: 'Munduk', title: 'Spa y cascada en la villa', text: 'Masaje con vistas a la selva y visita a la cascada de Munduk en plantación de café.', price: '50 – 140 €/persona', time: '09:30 – 17:00', wazeQuery: 'Munduk Waterfall Bali', image: IMG.villa, order: 8 },
  { category: 'activity', zone: 'Ubud', title: 'Monkey Forest', text: 'Reserva natural con banianos centenarios y monos macacos. Paseo corto desde el centro.', price: '~4 €/persona', time: '09:00 – 18:00', wazeQuery: 'Ubud Monkey Forest', image: IMG.jungle, order: 9 },
  { category: 'activity', zone: 'Ubud', title: 'Mercado de Ubud', text: 'Mercado artesanal de plata, madera, textiles y especias. Regateo parte de la experiencia.', price: 'Libre', time: '06:00 – 18:00', wazeQuery: 'Ubud Market', image: IMG.market, order: 10 },

  // TIPS
  { category: 'tip', zone: 'General', title: 'Visado y entrada', text: 'Visado a la llegada (VoA) de 30 días, ~30 €. Pasaporte con vigencia mínima 6 meses. Pasaje de salida obligatorio.', price: '~30 €/persona', time: 'Aeropuerto', order: 1 },
  { category: 'tip', zone: 'General', title: 'Moneda y pagos', text: 'Rupia indonesia (IDR). Tarjeta sin comisiones + efectivo para warungs y transportes. Aprox. 1 € ≈ 17.000 IDR.', price: '—', time: '—', order: 2 },
  { category: 'tip', zone: 'General', title: 'Sim y conexión', text: 'eSIM Telkomsel o XL a la llegada. Cobertura buena salvo en zonas de selva y mar abierto.', price: '8 – 15 €/15 días', time: 'Aeropuerto', order: 3 },
  { category: 'tip', zone: 'General', title: 'Seguro de viaje', text: 'Seguro con cobertura de actividades acuáticas y evacuación. Recomendado IATI o Heymondo.', price: '40 – 90 €/persona', time: 'Antes de salir', order: 4 },
  { category: 'tip', zone: 'General', title: 'Cuidado con el sol y el mar', text: 'Protector reef-safe, camiseta UV para snorkel e hidratación constante. Agua embotellada siempre.', price: '—', time: '—', order: 5 },
  { category: 'tip', zone: 'General', title: 'Mejor temporada', text: 'Agosto es temporada seca: calor suave, baja humedad y buen mar. Es también temporada alta: reservar con antelación.', price: '—', time: '—', order: 6 },
]

async function main() {
  console.log('🌱 Seeding Nusa Travel OS…')

  // Clean everything. The app starts with NO trip: the user generates their
  // own itinerary from the planner form on Inicio. Only the reference Guide
  // (transport / restaurants / beaches / activities / tips) is seeded.
  await db.suggestion.deleteMany()
  await db.day.deleteMany()
  await db.guideEntry.deleteMany()
  await db.trip.deleteMany()

  // (itinerary array kept above for reference, but no longer seeded — the
  //  LLM generates the days from the user's preferences on Inicio.)

  for (const g of guide) {
    await db.guideEntry.create({
      data: {
        category: g.category,
        zone: g.zone,
        title: g.title,
        text: g.text,
        price: g.price ?? null,
        time: g.time ?? null,
        link: g.link ?? null,
        wazeQuery: g.wazeQuery && g.wazeQuery.length ? g.wazeQuery : null,
        image: g.image ?? null,
        order: g.order,
      },
    })
  }

  console.log('✅ Seed completado (sin viaje — el usuario lo genera desde Inicio)')
  console.log(`   Guide entries: ${guide.length}`)
  console.log(`   Trip: ninguno (vacío)`)
  console.log(`   Days: 0 (vacío)`)
  console.log(`   Suggestions: 0`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })

// keep import used to avoid tree-shake noise
void readFileSync
