import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const elephants = [
  // ─── BALI (10) ───
  {
    order: 1,
    name: "Mason Elephant Park & Lodge",
    zone: "Ubud",
    subzone: "Taro",
    region: "Bali",
    description: "El parque de elefantes más famoso de Bali. Alberga más de 30 elefantes de Sumatra rescatados en un entorno de selva tropical de 3,5 hectáreas. Ofrece paseos a lomos de elefante, alimentación interactiva, espectáculos de baño y un museo dedicado a estos animales. Cuenta con restaurante con vistas al parque y alojamiento en lodges exclusivos.",
    tipoActividad: "Santuario y Parque",
    dificultad: "Fácil",
    duracion: "3-5 horas",
    mejorEpoca: "Todo el año (seco abr-oct)",
    queVer: "Elefantes bañándose en el lago, demostración de pintura artística, crías de elefante jugando, museo del elefante con fósiles de 15.000 años",
    peligro: "Seguro. Los elefantes están acostumbrados al contacto humano. Seguir siempre las instrucciones de los mahout (cuidadores). No dar comida no autorizada.",
    address: "Jl. Raya Taro, Tegallalang, Gianyar, Bali 80561",
    lat: -8.4305,
    lng: 115.2735,
    wazeUrl: "https://www.waze.com/ul?q=Mason+Elephant+Park+Taro+Bali&navigate=yes",
    webUrl: "https://www.elephantparkbali.com",
    rating: 4.7,
  },
  {
    order: 2,
    name: "Bali Elephant Camp",
    zone: "Ubud",
    subzone: "Carangsari",
    region: "Bali",
    description: "Campamento de elefantes situado en un valle verde junto al río Petanu. Ofrece paseos de 30 minutos por la selva y el río, además de interacción directa con los animales. Ideal para familias que buscan una experiencia íntima sin las multitudes de los parques grandes. Incluye almuerzo balinés con vistas al río.",
    tipoActividad: "Paseo en Elefante",
    dificultad: "Fácil",
    duracion: "2-3 horas",
    mejorEpoca: "Todo el año",
    queVer: "Ruta por la selva tropical cruzando el río Petanu, baños de elefantes, interacción con crías, vistas al valle de Carangsari",
    peligro: "Seguro. Se proporciona equipo de seguridad para el paseo. Los elefantes están bien entrenados y supervisados por mahout certificados.",
    address: "Carangsari, Petanu River Valley, Gianyar, Bali",
    lat: -8.4510,
    lng: 115.2890,
    wazeUrl: "https://www.waze.com/ul?q=Bali+Elephant+Camp+Carangsari&navigate=yes",
    webUrl: "https://www.balielephantcamp.com",
    rating: 4.4,
  },
  {
    order: 3,
    name: "Elephant Safari Park Lodge",
    zone: "Ubud",
    subzone: "Taro",
    region: "Bali",
    description: "Experiencia premium de lujo combinando alojamiento en villas con vistas directas al parque de elefantes. Los huéspedes pueden alimentar a los elefantes desde la terraza de su habitación, disfrutar de desayunos con vista a la zona de baño y participar en sesiones privadas con los mahout. El lodge incluye spa, piscina infinita y restaurante gourmet.",
    tipoActividad: "Lodge y Experiencia Premium",
    dificultad: "Fácil",
    duracion: "1-2 noches",
    mejorEpoca: "Todo el año (mejor abr-oct)",
    queVer: "Elefantes desde la terraza de la villa, safari privado al amanecer, sesión de baño con elefantes, cena bajo las estrellas con vistas al parque",
    peligro: "Seguro. Experiencia controlada y supervisada. Los elefantes del parque están habituados a la presencia de huéspedes.",
    address: "Jl. Raya Taro, Tegallalang, Gianyar, Bali 80561",
    lat: -8.4295,
    lng: 115.2740,
    wazeUrl: "https://www.waze.com/ul?q=Elephant+Safari+Park+Lodge+Taro&navigate=yes",
    webUrl: "https://www.elephantsafariparklodge.com",
    rating: 4.8,
  },
  {
    order: 4,
    name: "Bali Adventure Elephants",
    zone: "Gianyar",
    subzone: "Saba Bay",
    region: "Bali",
    description: "Única experiencia de paseo en elefante por la playa en Bali. Los elefantes caminan por la arena negra volcánica de la bahía de Saba con el océano Índico de fondo. Combina la majestuosidad de los animales con un paisaje costero espectacular. Incluye tiempo de interacción y alimentación después del paseo.",
    tipoActividad: "Paseo en Playa",
    dificultad: "Fácil",
    duracion: "2 horas",
    mejorEpoca: "Mayo-octubre (estación seca)",
    queVer: "Paseo de elefantes por la playa de arena negra, vistas al volcán Agung, bañarse con los elefantes en piscina, alimentación de elefantes",
    peligro: "Seguro. Los elefantes caminan a paso lento por la playa. Las olas son suaves en esta bahía. Usar protector solar biodegradable.",
    address: "Saba Bay, Gianyar, Bali",
    lat: -8.5120,
    lng: 115.3210,
    wazeUrl: "https://www.waze.com/ul?q=Bali+Adventure+Elephants+Saba+Bay&navigate=yes",
    webUrl: "",
    rating: 4.3,
  },
  {
    order: 5,
    name: "Sacred Monkey Forest Elephant Show",
    zone: "Ubud",
    subzone: "Centro",
    region: "Bali",
    description: "Espectáculo tradicional balinés donde elefantes entrenados realizan demostraciones de pintura artística, música y danza al ritmo del gamelán. Se celebra en un escenario al aire libre rodeado de bosque sagrado. Una experiencia cultural única que combina el arte balinés con la majestuosidad de los elefantes. Disponible bajo reserva.",
    tipoActividad: "Espectáculo Cultural",
    dificultad: "Fácil",
    duracion: "1 hora",
    mejorEpoca: "Todo el año",
    queVer: "Demostración de pintura con trompa, elefantes tocando instrumentos tradicionales, baile ceremonial balinés, exhibición de inteligencia animal",
    peligro: "Seguro. Espectáculo supervisado con animales entrenados durante años. Área de público separada por barrera natural.",
    address: "Jl. Monkey Forest, Ubud, Gianyar, Bali",
    lat: -8.5186,
    lng: 115.2588,
    wazeUrl: "https://www.waze.com/ul?q=Ubud+Monkey+Forest+Bali&navigate=yes",
    webUrl: "",
    rating: 4.1,
  },
  {
    order: 6,
    name: "Taro Elephant Conservation",
    zone: "Ubud",
    subzone: "Taro",
    region: "Bali",
    description: "Programa de conservación educativo enfocado en la protección del elefante de Sumatra, especie en peligro crítico. Los visitantes participan en talleres sobre ecología, comportamiento elefante y esfuerzos de conservación. Incluye recorrido por las instalaciones de rescate, charla con veterinarios y sesión de enriquecimiento ambiental con los elefantes.",
    tipoActividad: "Conservación y Educación",
    dificultad: "Fácil",
    duracion: "3 horas",
    mejorEpoca: "Todo el año",
    queVer: "Instalaciones veterinarias, centro de cría, sesiones de enriquecimiento ambiental, charla educativa sobre el elefante de Sumatra, certificado de participante",
    peligro: "Seguro. Experiencia educativa sin contacto directo de riesgo. Las sesiones de enriquecimiento están supervisadas por personal especializado.",
    address: "Jl. Raya Taro, Tegallalang, Gianyar, Bali 80561",
    lat: -8.4310,
    lng: 115.2750,
    wazeUrl: "https://www.waze.com/ul?q=Taro+Elephant+Conservation+Bali&navigate=yes",
    webUrl: "",
    rating: 4.6,
  },
  {
    order: 7,
    name: "Elephant Bathing Experience Ubud",
    zone: "Ubud",
    subzone: "Kenderan",
    region: "Bali",
    description: "Experiencia de baño interactivo con elefantes en un río de montaña cristalino. Los visitantes entran al agua con los elefantes y participan activamente en su higiene diaria usando esponjas naturales y cepillos bajo la supervisión de mahout. Una experiencia sensorial única: sentir la textura de la piel del elefante mientras este se sumerge y juega en el agua.",
    tipoActividad: "Baño Interactivo",
    dificultad: "Medio",
    duracion: "1.5 horas",
    mejorEpoca: "Todo el año (mejor abr-oct)",
    queVer: "Baño completo de elefantes en el río, juego con mangueras y agua, sesión de cepillado, elefantes sumergiéndose y lanzando agua con la trompa",
    peligro: "Bajo riesgo. Los elefantes son dóciles en el agua pero pueden salpicar con fuerza. Usar calzado que se pueda mojar. Las piedras del río pueden ser resbaladizas.",
    address: "Kenderan, Tegallalang, Gianyar, Bali",
    lat: -8.4400,
    lng: 115.2800,
    wazeUrl: "https://www.waze.com/ul?q=Elephant+Bathing+Experience+Kenderan+Ubud&navigate=yes",
    webUrl: "",
    rating: 4.5,
  },
  {
    order: 8,
    name: "Night Safari con Elefantes Bali",
    zone: "Gianyar",
    subzone: "Singapadu",
    region: "Bali",
    description: "Safari nocturno donde los visitantes recorren las instalaciones del parque en un carro tirado por elefantes bajo la iluminación de antorchas y luces cálidas. La experiencia incluye cena buffet balinesa, espectáculo de fuegos y una visita al área de cría donde se pueden ver los elefantes durmiendo. Ambiente mágico y romántico ideal para parejas.",
    tipoActividad: "Safari Nocturno",
    dificultad: "Fácil",
    duracion: "3 horas (desde las 18:00)",
    mejorEpoca: "Todo el año",
    queVer: "Recorrido nocturno en carro de elefante, cena buffet con vistas, elefantes bajo iluminación artificial, espectáculo de baile Kecak con fuegos, crías durmiendo",
    peligro: "Seguro. Ruta iluminada y supervisada. Los elefantes están en su horario de descanso y son más tranquilos. Caminar con cuidado por las zonas no pavimentadas.",
    address: "Singapadu, Gianyar, Bali",
    lat: -8.5420,
    lng: 115.2680,
    wazeUrl: "https://www.waze.com/ul?q=Night+Safari+Elephants+Singapadu+Bali&navigate=yes",
    webUrl: "",
    rating: 4.4,
  },
  {
    order: 9,
    name: "Elephant Art Studio Bali",
    zone: "Ubud",
    subzone: "Peliatan",
    region: "Bali",
    description: "Taller de arte donde los elefantes pintan lienzos con la trompa bajo la guía de sus mahout. Los visitantes pueden observar el proceso creativo y adquirir las obras originales como recuerdo. También ofrece talleres de cerámica con temática elefante para niños y adultos. Una fusión única entre arte y naturaleza.",
    tipoActividad: "Arte y Creatividad",
    dificultad: "Fácil",
    duracion: "1.5 horas",
    mejorEpoca: "Todo el año",
    queVer: "Demostración de pintura en vivo, galería de obras de elefantes, taller de cerámica, tienda de arte con recuerdos únicos, sesión de fotos con el artista elefante",
    peligro: "Seguro. Los elefantes pintan en un área delimitada. No hay contacto directo durante la pintura. Zona de observación cubierta.",
    address: "Peliatan, Ubud, Gianyar, Bali",
    lat: -8.5090,
    lng: 115.2630,
    wazeUrl: "https://www.waze.com/ul?q=Elephant+Art+Studio+Peliatan+Ubud&navigate=yes",
    webUrl: "",
    rating: 4.2,
  },
  {
    order: 10,
    name: "Bali Elephant Wellness Retreat",
    zone: "Ubud",
    subzone: "Kedewatan",
    region: "Bali",
    description: "Retiro de bienestar de día completo que combina meditación junto a los elefantes, yoga matutino con vistas al parque, sesión de spa balinés y un almuerzo orgánico saludable. Los elefantes pasean libremente por los jardines mientras los participantes disfrutan de tratamientos. Experiencia de desconexión total en un entorno natural extraordinario.",
    tipoActividad: "Bienestar y Spa",
    dificultad: "Fácil",
    duracion: "6 horas (día completo)",
    mejorEpoca: "Todo el año (mejor jun-sep)",
    queVer: "Yoga al amanecer con elefantes de fondo, meditación guiada en el bosque, tratamiento spa balinés tradicional, jardines de hierbas medicinales, almuerzo orgánico con vistas",
    peligro: "Seguro. No hay montura ni contacto directo intensivo. Los elefantes están en un área adyacente separada por seto natural. Ambiente relajado y controlado.",
    address: "Kedewatan, Ubud, Gianyar, Bali",
    lat: -8.4760,
    lng: 115.2480,
    wazeUrl: "https://www.waze.com/ul?q=Bali+Elephant+Wellness+Retreat+Kedewatan&navigate=yes",
    webUrl: "",
    rating: 4.6,
  },

  // ─── SUMATRA (8) ───
  {
    order: 11,
    name: "Centro de Conservación de Elefantes de Sumatra (PKGS)",
    zone: "Aceh",
    subzone: "Lhokseumawe",
    region: "Borneo y Sumatra",
    description: "El centro de conservación más importante de elefantes de Sumatra, especie en peligro crítico de extinción. Alberga elefantes rescatados de conflictos con humanos y ofrece programas de rehabilitación. Los visitantes pueden observar a los elefantes en su hábitat natural, participar en sesiones de alimentación y aprender sobre los esfuerzos de conservación de la subespecie más amenazada de Asia.",
    tipoActividad: "Conservación y Rescate",
    dificultad: "Medio",
    duracion: "4-6 horas",
    mejorEpoca: "Marzo-octubre (estación seca)",
    queVer: "Elefantes de Sumatra en hábitat semi-natural, centro de rehabilitación, sesión de alimentación, charla de conservación, recorrido por la jungla circundante",
    peligro: "Moderado. Los elefantes rescatados pueden ser impredecibles. Mantener distancia de seguridad indicada por los guías. Zona de selva tropical: usar repelente de mosquitos y ropa manga larga.",
    address: "Jl. Medan-Banda Aceh, Lhokseumawe, Aceh, Sumatra",
    lat: 5.1780,
    lng: 97.1250,
    wazeUrl: "https://www.waze.com/ul?q=Sumatran+Elephant+Conservation+Center+Lhokseumawe&navigate=yes",
    webUrl: "",
    rating: 4.5,
  },
  {
    order: 12,
    name: "Taman Safari Indonesia - Sección Elefantes",
    zone: "Java Occidental",
    subzone: "Cisarua",
    region: "Borneo y Sumatra",
    description: "Sección especializada en elefantes dentro del famoso Taman Safari de Java. Alberga elefantes de Sumatra y elefantes asiáticos en recintos que simulan su hábitat natural. Ofrece safaris en jeep, espectáculo de elefantes y programa de adopción simbólica. El parque combina la experiencia de safari africano con la fauna endémica indonesia.",
    tipoActividad: "Safari y Parque",
    dificultad: "Fácil",
    duracion: "4-5 horas",
    mejorEpoca: "Todo el año (mejor abr-oct)",
    queVer: "Safari en jeep entre elefantes en semi-libertad, espectáculo diario de elefantes, crías de elefante en el centro de cría, zona de interacción y alimentación",
    peligro: "Seguro. Recintos diseñados con barreras de seguridad. Los elefantes del safari están en área delimitada. Seguir las normas del parque: no bajar del vehículo ni dar comida.",
    address: "Jl. Raya Puncak No. 601, Cisarua, Bogor, Java Occidental",
    lat: -6.7030,
    lng: 106.9770,
    wazeUrl: "https://www.waze.com/ul?q=Taman+Safari+Indonesia+Cisarua&navigate=yes",
    webUrl: "https://www.tamansafari.com",
    rating: 4.6,
  },
  {
    order: 13,
    name: "Way Kambas National Park - Elephant Training Center",
    zone: "Lampung",
    subzone: "Way Jepara",
    region: "Borneo y Sumatra",
    description: "Centro de entrenamiento y conservación de elefantes dentro del Parque Nacional Way Kambas, uno de los últimos refugios del elefante de Sumatra. Los elefantes son entrenados para labores de conservación y patrulla forestal. Los visitantes pueden hacer safaris en elefante por la selva, observar vida silvestre y visitar el centro de cría. Experiencia auténtica de conservación.",
    tipoActividad: "Safari en Selva",
    dificultad: "Difícil",
    duracion: "Día completo (8-10 horas)",
    mejorEpoca: "Mayo-septiembre (estación seca)",
    queVer: "Safari en elefante por selva tropical primaria, avistamiento de rinocerontes de Java, centro de cría de elefantes, vida nocturna con guided night walk",
    peligro: "Alto. Selva tropical con fauna peligrosa (serpientes, insectos, mamíferos). Obligatorio ir con guía autorizado. Vacunas recomendadas (tétanos, fiebre amarilla). Llevar botiquín completo.",
    address: "Way Jepara, Lampung, Sumatra",
    lat: -5.0750,
    lng: 105.7540,
    wazeUrl: "https://www.waze.com/ul?q=Way+Kambas+Elephant+Training+Center&navigate=yes",
    webUrl: "",
    rating: 4.7,
  },
  {
    order: 14,
    name: "Bukit Barisan Selatan - Elephant Watching",
    zone: "Lampung",
    subzone: "Tanggamus",
    region: "Borneo y Sumatra",
    description: "Avistamiento de elefantes salvajes en su hábitat natural dentro del Parque Nacional Bukit Barisan Selatan. Se realizan expediciones guiadas al amanecer y atardecer, cuando los elefantes salen a los claros de la selva. Una de las pocas experiencias en Indonesia donde se pueden ver elefantes completamente salvajes. También se pueden avistar tigres de Sumatra y tapirs.",
    tipoActividad: "Avistamiento Salvaje",
    dificultad: "Difícil",
    duracion: "2 días (expedición completa)",
    mejorEpoca: "Junio-septiembre",
    queVer: "Manada de elefantes salvajes en clearing, huellas y rastros, avistamiento de aves endémicas, flora de selva tropical de tierras bajas",
    peligro: "Alto. Elefantes salvajes son impredecibles. Mantener mínimo 100 metros de distancia. Selva primaria con riesgo de serpientes, mosquitos y leeches. Guía obligatorio con experiencia en fauna salvaje.",
    address: "Tanggamus, Lampung, Sumatra",
    lat: -5.1500,
    lng: 104.7500,
    wazeUrl: "https://www.waze.com/ul?q=Bukit+Barisan+Selatan+Elephant+Watching&navigate=yes",
    webUrl: "",
    rating: 4.8,
  },
  {
    order: 15,
    name: "Elephant Patrol Experience - Minas",
    zone: "Riau",
    subzone: "Minas",
    region: "Borneo y Sumatra",
    description: "Acompañar a los mahout en su patrulla diaria por las plantaciones y selva de Riau, donde los elefantes entrenados ayudan a alejar a los elefantes salvajes de las zonas cultivadas. Los visitantes se integran en el equipo de conservación por un día completo, aprendiendo técnicas de manejo y el conflicto humano-elefante en Sumatra. Experiencia única e inmersiva.",
    tipoActividad: "Patrulla de Conservación",
    dificultad: "Difícil",
    duracion: "Día completo (10 horas)",
    mejorEpoca: "Abril-octubre",
    queVer: "Patrulla en elefante por zona de conflicto, demostración de técnicas de disuasión, encuentro potencial con elefantes salvajes, vida en el campamento de mahout",
    peligro: "Alto. Zona de conflicto humano-elefante real. Los elefantes salvajes pueden ser agresivos si se sienten amenazados. Condición física necesaria para montar varias horas. Clima tropical húmedo extremo.",
    address: "Minas, Siak, Riau, Sumatra",
    lat: 0.9330,
    lng: 102.1830,
    wazeUrl: "https://www.waze.com/ul?q=Elephant+Patrol+Minas+Riau&navigate=yes",
    webUrl: "",
    rating: 4.6,
  },
  {
    order: 16,
    name: "PLG Seblat Elephant Conservation Center",
    zone: "Bengkulu",
    subzone: "Seluma",
    region: "Borneo y Sumatra",
    description: "Centro de conservación gestionado por el gobierno indonesio especializado en el entrenamiento de elefantes para la conservación forestal. Los elefantes del centro participan en patrullas contra la tala ilegal. Los visitantes pueden observar los entrenamientos diarios, participar en sesiones de enriquecimiento ambiental y hacer un trekking corto en elefante por el bosque secundario.",
    tipoActividad: "Centro de Conservación",
    dificultad: "Medio",
    duracion: "4-5 horas",
    mejorEpoca: "Mayo-septiembre",
    queVer: "Demostración de entrenamiento de elefantes, patrulla de conservación, trekking en elefante por bosque, vivero de plantas nativas, interacción con crías",
    peligro: "Moderado. Los elefantes de trabajo son más grandes y fuertes que los de safari. Seguir instrucciones del mahout estrictamente. Zona rural: llevar agua, protector solar y repelente.",
    address: "Seluma, Bengkulu, Sumatra",
    lat: -4.1500,
    lng: 102.3500,
    wazeUrl: "https://www.waze.com/ul?q=PLG+Seblat+Elephant+Conservation+Center&navigate=yes",
    webUrl: "",
    rating: 4.4,
  },
  {
    order: 17,
    name: "Elephant Hospital de Sumatra",
    zone: "Aceh",
    subzone: "Banda Aceh",
    region: "Borneo y Sumatra",
    description: "Hospital veterinario especializado en el tratamiento y rehabilitación de elefantes heridos por trampas de cazadores furtivos o por conflictos humanos. Los visitantes pueden realizar un tour educativo por las instalaciones, conocer los casos de los pacientes actuales y colaborar con el programa de adopción. Experiencia conmovedora que muestra la realidad de la conservación.",
    tipoActividad: "Tour Educativo y Veterinario",
    dificultad: "Fácil",
    duracion: "2-3 horas",
    mejorEpoca: "Todo el año",
    queVer: "Instalaciones veterinarias, elefantes en recuperación, quirófano, laboratorio, sala de maternidad, presentación de casos clínicos reales",
    peligro: "Seguro. Los pacientes están en recintos de cuarentena. No hay contacto directo con los elefantes heridos. Zona hospitalaria: seguir protocolos de higiene indicados.",
    address: "Banda Aceh, Aceh, Sumatra",
    lat: 5.5500,
    lng: 95.3200,
    wazeUrl: "https://www.waze.com/ul?q=Sumatran+Elephant+Hospital+Banda+Aceh&navigate=yes",
    webUrl: "",
    rating: 4.5,
  },
  {
    order: 18,
    name: "Riau Elephant Flying Camp",
    zone: "Riau",
    subzone: "Dumai",
    region: "Borneo y Sumatra",
    description: "Campamento itinerante que se instala en diferentes zonas de Riau siguiendo las rutas migratorias de los elefantes. Ofrece la experiencia más auténtica de convivencia con elefantes: los visitantes duermen en tiendas en medio de la selva, despiertan con los sonidos de la naturaleza y acompañan a los elefantes en sus rutinas diarias. Aventura pura para viajeros experimentados.",
    tipoActividad: "Campamento de Aventura",
    dificultad: "Difícil",
    duracion: "2-3 días",
    mejorEpoca: "Junio-agosto",
    queVer: "Campamento en selva, rutina completa con elefantes, avistamiento nocturno, cocinar con ingredientes locales, rutas migratorias de elefantes",
    peligro: "Alto. Campamento en selva tropical sin comodidades modernas. Fauna peligrosa (serpientes, escorpiones, mosquitos portadores de malaria). Necesaria buena condición física y resistencia al calor. Guía experto obligatorio.",
    address: "Dumai, Riau, Sumatra",
    lat: 1.6700,
    lng: 102.0800,
    wazeUrl: "https://www.waze.com/ul?q=Riau+Elephant+Flying+Camp+Dumai&navigate=yes",
    webUrl: "",
    rating: 4.3,
  },

  // ─── JAVA (4) ───
  {
    order: 19,
    name: "Taman Giri Jati Elephant Center",
    zone: "Java Central",
    subzone: "Magelang",
    region: "Java",
    description: "Centro de elefantes cerca de Borobudur que combina la experiencia cultural de los templos con la interacción con elefantes. Los elefantes participan en ceremonias tradicionales javanesas y ofrecen paseos con vistas al volcán Merapi. El centro trabaja con comunidades locales en programas de educación ambiental y turismo responsable.",
    tipoActividad: "Cultural y Interacción",
    dificultad: "Fácil",
    duracion: "2-3 horas",
    mejorEpoca: "Abril-octubre",
    queVer: "Paseo con vistas al volcán Merapi y Borobudur, ceremonia de bienvenida javanesa, alimentación de elefantes, demostración de habilidades tradicionales",
    peligro: "Seguro. Centro con buen historial de seguridad. Los elefantes están habituados a turistas. Zona volcánica: informarse sobre la actividad del Merapi antes de visitar.",
    address: "Magelang, Java Central",
    lat: -7.5100,
    lng: 110.3800,
    wazeUrl: "https://www.waze.com/ul?q=Taman+Giri+Jati+Elephant+Center+Magelang&navigate=yes",
    webUrl: "",
    rating: 4.3,
  },
  {
    order: 20,
    name: "Zoo de Surabaya - Pabean Elephants",
    zone: "Java Oriental",
    subzone: "Surabaya",
    region: "Java",
    description: "El zoológico más antiguo de Indonesia alberga una de las colecciones de elefantes más completas del sudeste asiático. El recinto de elefantes ha sido renovado recientemente con espacios amplios, piscina y zona de enriquecimiento ambiental. Los visitantes pueden alimentar a los elefantes, asistir a charlas educativas y participar en el programa de voluntariado.",
    tipoActividad: "Zoológico y Educación",
    dificultad: "Fácil",
    duracion: "2-3 horas",
    mejorEpoca: "Todo el año",
    queVer: "Colección de elefantes asiáticos, recinto renovado con piscina, sesiones de alimentación, charla educativa diaria, programa de enriquecimiento ambiental",
    peligro: "Seguro. Instalaciones de zoológico con estándares internacionales. Barreras de seguridad en todas las zonas. Zonas sombreadas limitadas: llevar gorra y agua.",
    address: "Jl. Setail No. 1, Surabaya, Java Oriental",
    lat: -7.2950,
    lng: 112.7370,
    wazeUrl: "https://www.waze.com/ul?q=Kebun+Binatang+Surabaya+Elephants&navigate=yes",
    webUrl: "",
    rating: 4.1,
  },
  {
    order: 21,
    name: "Merapi Elephant Trek - Yogyakarta",
    zone: "Yogyakarta",
    subzone: "Kaliurang",
    region: "Java",
    description: "Trekking en elefante por las laderas del volcán Merapi, una de las experiencias más singulares de Java. La ruta transcurre por plantaciones de café, bosques de selva y aldeas tradicionales con vistas espectaculares al volcán activo. El trekking incluye parada en una aldea para probar kopi luwak y snacks locales.",
    tipoActividad: "Trekking en Volcán",
    dificultad: "Medio",
    duracion: "3-4 horas",
    mejorEpoca: "Mayo-septiembre",
    queVer: "Vistas panorámicas del volcán Merapi, plantaciones de café y cacao, aldeas javanesas tradicionales, flora de montaña tropical",
    peligro: "Moderado. Actividad volcánica del Merapi: consultar nivel de alerta antes de ir. El terreno es irregular y puede ser resbaladizo. Protección solar indispensable. Los elefantes pueden sentir inquietud si hay actividad sísmica.",
    address: "Kaliurang, Yogyakarta, Java",
    lat: -7.6050,
    lng: 110.4250,
    wazeUrl: "https://www.waze.com/ul?q=Merapi+Elephant+Trek+Kaliurang&navigate=yes",
    webUrl: "",
    rating: 4.4,
  },
  {
    order: 22,
    name: "Ujung Kulon Elephant Safari",
    zone: "Banten",
    subzone: "Ujung Kulon",
    region: "Java",
    description: "Safari en elefante por el Parque Nacional Ujung Kulon, Patrimonio de la Humanidad por la UNESCO y último refugio del rinoceronte de Java. La ruta recorre selva tropical primaria, playas vírgenes y manglares. Posibilidad de avistar elefantes javaneses en estado semi-salvaje, además de rinocerontes, búfalos y monos. Experiencia de safari auténtico y virgen.",
    tipoActividad: "Safari en Parque Nacional",
    dificultad: "Difícil",
    duracion: "2 días (expedición completa)",
    mejorEpoca: "Abril-octubre",
    queVer: "Selva tropical primaria de Ujung Kulon, playas vírgenes, posible avistamiento de rinoceronte de Java, elefantes semi-salvajes, manglares, fauna marina en snorkel",
    peligro: "Alto. Parque nacional remoto sin infraestructura médica. Fauna salvaje peligrosa. Selva densa con riesgo de extravío. Obligatorio permiso del parque y guía local. Equipo de supervivencia recomendado.",
    address: "Ujung Kulon National Park, Banten, Java",
    lat: -6.7500,
    lng: 105.3330,
    wazeUrl: "https://www.waze.com/ul?q=Ujung+Kulon+National+Park+Elephant+Safari&navigate=yes",
    webUrl: "",
    rating: 4.7,
  },

  // ─── BORNEO (3) ───
  {
    order: 23,
    name: "Borneo Elephant Sanctuary - Kinabatangan",
    zone: "Sabah",
    subzone: "Kinabatangan River",
    region: "Borneo y Sumatra",
    description: "Santuario dedicado al elefante pigmeo de Borneo, la subespecie más pequeña y rara de elefante asiático. Situado a orillas del río Kinabatangan, el santuario ofrece observación de elefantes desde barcos, caminatas guiadas por la selva y programas de voluntariado en conservación. Los elefantes se acercan al río al atardecer, creando escenas espectaculares.",
    tipoActividad: "Santuario y Avistamiento",
    dificultad: "Medio",
    duracion: "2-3 días",
    mejorEpoca: "Marzo-octubre",
    queVer: "Elefantes pigmeos de Borneo en el río Kinabatangan, safari fluvial al atardecer, selva tropical de Borneo, aves exóticas, proboscis monos, orangutanes",
    peligro: "Moderado. Los elefantes salvajes se observan desde el barco: no hay contacto directo. Río con corrientes: usar chaleco salvavidas. Selva con mosquitos y leeches: repelente y botas altas recomendadas.",
    address: "Kinabatangan River, Sabah, Borneo Malayo",
    lat: 5.5000,
    lng: 118.3000,
    wazeUrl: "https://www.waze.com/ul?q=Borneo+Elephant+Sanctuary+Kinabatangan&navigate=yes",
    webUrl: "",
    rating: 4.7,
  },
  {
    order: 24,
    name: "Danum Valley Elephant Tracking",
    zone: "Sabah",
    subzone: "Danum Valley",
    region: "Borneo y Sumatra",
    description: "Expedición de rastreo de elefantes en una de las selvas tropicales más antiguas del mundo (130 millones de años). Los visitantes acompañan a guías expertos y rastreadores indígenas siguiendo huellas, heces y marcas de elefantes por la selva primaria. El programa incluye estancia en un lodge de investigación científica y caminatas nocturnas para observar fauna.",
    tipoActividad: "Expedición de Rastreo",
    dificultad: "Difícil",
    duracion: "3-4 días",
    mejorEpoca: "Junio-septiembre",
    queVer: "Selva tropical primaria de 130M años, huellas frescas de elefante, canopia desde torre de observación, vida nocturna (cíveta, loris, búhos), cascadas escondidas",
    peligro: "Alto. Selva virgen sin caminos. Posibles encuentros con elefantes salvajes, jabalíes, serpientes venenosas. Condición física excelente necesaria. Clima extremadamente húmedo. Guía indígena obligatorio.",
    address: "Danum Valley Conservation Area, Sabah, Borneo Malayo",
    lat: 4.9500,
    lng: 117.8000,
    wazeUrl: "https://www.waze.com/ul?q=Danum+Valley+Elephant+Tracking&navigate=yes",
    webUrl: "",
    rating: 4.9,
  },
  {
    order: 25,
    name: "Tabin Wildlife Reserve - Elephants",
    zone: "Sabah",
    subzone: "Tabin",
    region: "Borneo y Sumatra",
    description: "Reserva natural que combina la observación de elefantes pigmeos con el avistamiento de otras especies emblemáticas de Borneo. Cuenta con un lodge junto a un lago natural donde los elefantes vienen a beber. Ofrece safaris nocturnos en jeep, caminatas por la selva y visitas a las lagunas de barro donde los elefantes se bañan. Ideal para fotógrafos de naturaleza.",
    tipoActividad: "Reserva y Safari",
    dificultad: "Medio",
    duracion: "2 días",
    mejorEpoca: "Abril-octubre",
    queVer: "Elefantes pigmeos en laguna natural, safari nocturno en jeep, avistamiento de orangutanes, hornbills y gibones, lago Lipad al amanecer, mud volcanoes",
    peligro: "Moderado. Elefantes observados desde vehículo o plataforma segura. Selva tropical con insectos y reptiles. Rutas en jeep por pistas forestales irregulares. Llevar ropa de manga larga y repelente potente.",
    address: "Tabin Wildlife Reserve, Lahad Datu, Sabah, Borneo Malayo",
    lat: 5.1500,
    lng: 118.7500,
    wazeUrl: "https://www.waze.com/ul?q=Tabin+Wildlife+Reserve+Elephants&navigate=yes",
    webUrl: "",
    rating: 4.6,
  },

  // ─── SULAWESI (2) ───
  {
    order: 26,
    name: "Lore Lindu Elephant Trail",
    zone: "Sulawesi Central",
    subzone: "Palolo Valley",
    region: "Sulawesi y Raja Ampat",
    description: "Ruta de trekking por el Parque Nacional Lore Lindu que sigue antiguos senderos utilizados por elefantes pigmeos en tiempos prehistóricos. Aunque los elefantes ya no habitan la zona, el parque conserva petroglifos y megalitos que documentan su presencia histórica. El trekking combina naturaleza, arqueología y cultura con las comunidades Kaili locales.",
    tipoActividad: "Trekking Cultural y Natural",
    dificultad: "Medio",
    duracion: "1 día completo",
    mejorEpoca: "Mayo-octubre",
    queVer: "Petroglifos de elefantes prehistóricos, megalitos de piedra de miles de años, selva montana de Sulawesi, cascadas de Palolo, aldeas Kaili tradicionales",
    peligro: "Moderado. Trekking por terreno montañoso irregular. Senderos pueden ser resbaladizos en época de lluvias. Fauna menos peligrosa que en Sumatra o Borneo. Guía local recomendado.",
    address: "Palolo Valley, Lore Lindu National Park, Sulawesi Central",
    lat: -1.2500,
    lng: 120.1500,
    wazeUrl: "https://www.waze.com/ul?q=Lore+Lindu+Elephant+Trail+Palolo&navigate=yes",
    webUrl: "",
    rating: 4.2,
  },
  {
    order: 27,
    name: "Minahasa Highland Elephant Heritage",
    zone: "Sulawesi del Norte",
    subzone: "Tomohon",
    region: "Sulawesi y Raja Ampat",
    description: "Centro de patrimonio elefante en las tierras altas de Minahasa que celebra la relación histórica entre los humanos y los elefantes en el norte de Sulawesi. Incluye un museo con fósiles de elefantes enanos de Sulawesi (extintos), un centro de educación ambiental y un sendero ecológico con réplicas a escala real. Combina perfectamente con una visita al mercado tradicional de Tomohon.",
    tipoActividad: "Museo y Patrimonio",
    dificultad: "Fácil",
    duracion: "2 horas",
    mejorEpoca: "Todo el año",
    queVer: "Fósiles de elefante enano de Sulawesi, réplicas a escala real, museo interactivo, sendero ecológico, vistas a los volcanes Lokon y Mahawu",
    peligro: "Seguro. Experiencia de museo al aire libre. Terreno llano y pavimentado. Zona volcánica: consultar actividad de los volcanes Lokon y Mahawu.",
    address: "Tomohon, Minahasa, Sulawesi del Norte",
    lat: 1.3200,
    lng: 124.8000,
    wazeUrl: "https://www.waze.com/ul?q=Minahasa+Elephant+Heritage+Tomohon&navigate=yes",
    webUrl: "",
    rating: 4.0,
  },
]

async function main() {
  console.log(`Seeding ${elephants.length} elephant activities...`)
  
  // Clear existing
  await db.elephantActivity.deleteMany()
  
  for (const e of elephants) {
    await db.elephantActivity.create({ data: e })
    console.log(`  ✓ ${e.order}. ${e.name} (${e.region})`)
  }
  
  const count = await db.elephantActivity.count()
  console.log(`\nDone! ${count} elephant activities seeded.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => db.$disconnect())